import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { openPath } from "@tauri-apps/plugin-opener";

// News tab — lists the HTML newsletters generated in
// ~/.ultron/cockpit/news/. Each newsletter is a full-page artifact, so
// the tab itself just gives a list, summary, and "open in browser" /
// "open in viewer" actions. Inline preview shows the title + first
// paragraphs; the real read happens in a system browser.

export type NewsEntry = {
  filename: string;
  path: string;
  generated_at: string | null;
  size_bytes: number;
  title: string | null;
  excerpt: string | null;
};

function formatBytes(b: number): string {
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1024 / 1024).toFixed(2)} MB`;
}

function dateFromName(name: string): string | null {
  // Names look like newsletter-2026-05-11.html — we surface the date.
  const m = name.match(/(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : null;
}

export function News() {
  const [items, setItems] = useState<NewsEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    invoke<NewsEntry[]>("list_news")
      .then((list) => {
        if (cancelled) return;
        setItems(list);
        setSelected(list[0]?.path ?? null);
        setError(null);
      })
      .catch((e) => {
        if (!cancelled) setError(String(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  function openExternalPath(p: string) {
    openPath(p).catch((e: unknown) => setError(String(e)));
  }

  const sel = items.find((i) => i.path === selected) ?? null;

  return (
    <div className="flex h-full">
      <div
        className="flex w-[44%] min-w-[420px] flex-col overflow-hidden border-r"
        style={{ borderColor: "var(--color-border)" }}
      >
        <header className="border-b px-5 py-4" style={{ borderColor: "var(--color-border)" }}>
          <h1 className="text-[18px] font-semibold leading-tight">News</h1>
          <p className="mt-1 text-[12px]" style={{ color: "var(--color-text-secondary)" }}>
            {items.length} newsletter{items.length === 1 ? "" : "s"} generated by ULTRON Times
          </p>
        </header>
        <div className="flex-1 overflow-auto p-2">
          {loading && (
            <div className="px-3 py-4 text-[12px]" style={{ color: "var(--color-text-tertiary)" }}>
              Loading…
            </div>
          )}
          {error && (
            <div
              className="m-2 rounded p-3 text-[12px]"
              style={{
                background: "rgba(248, 81, 73, 0.06)",
                border: "1px solid rgba(248, 81, 73, 0.22)",
                color: "var(--color-danger)",
              }}
            >
              {error}
            </div>
          )}
          {!loading && items.length === 0 && (
            <div
              className="m-2 rounded p-6 text-center text-[12.5px]"
              style={{
                background: "var(--color-surface-2)",
                border: "1px solid var(--color-border)",
                color: "var(--color-text-secondary)",
              }}
            >
              No newsletters yet. Run the news pipeline to generate one.
            </div>
          )}
          {items.map((n) => {
            const active = selected === n.path;
            const date = dateFromName(n.filename);
            return (
              <button
                key={n.path}
                type="button"
                onClick={() => setSelected(n.path)}
                className="block w-full rounded px-3 py-2 text-left transition-colors"
                style={{
                  background: active ? "var(--color-surface-3)" : "transparent",
                  border: `1px solid ${active ? "var(--color-border-strong)" : "transparent"}`,
                }}
              >
                <div className="flex items-baseline gap-2">
                  <span
                    className="text-[12.5px] font-medium"
                    style={{ color: "var(--color-text)" }}
                  >
                    {n.title ?? n.filename}
                  </span>
                  <span
                    className="ml-auto text-[10.5px] tabular-nums"
                    style={{ color: "var(--color-text-tertiary)" }}
                  >
                    {date ?? n.generated_at ?? ""}
                  </span>
                </div>
                {n.excerpt && (
                  <div
                    className="mt-1 truncate text-[11.5px]"
                    style={{ color: "var(--color-text-tertiary)" }}
                  >
                    {n.excerpt}
                  </div>
                )}
                <div
                  className="mt-1 text-[10.5px]"
                  style={{ color: "var(--color-text-faint)" }}
                >
                  {formatBytes(n.size_bytes)}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      <div className="flex-1 overflow-hidden">
        {sel ? (
          <div className="flex h-full flex-col overflow-hidden">
            <header
              className="flex items-center justify-between border-b px-5 py-4"
              style={{ borderColor: "var(--color-border)" }}
            >
              <div className="min-w-0">
                <h2 className="truncate text-[15px] font-semibold">
                  {sel.title ?? sel.filename}
                </h2>
                <div
                  className="mt-1 truncate text-[10.5px]"
                  style={{ fontFamily: "var(--font-mono)", color: "var(--color-text-faint)" }}
                  title={sel.path}
                >
                  {sel.path}
                </div>
              </div>
              <button
                type="button"
                onClick={() => openExternalPath(sel.path)}
                className="shrink-0 rounded px-3 py-1.5 text-[12px] font-medium transition-colors"
                style={{
                  background: "var(--color-accent)",
                  color: "var(--color-accent-text)",
                }}
              >
                Open in browser
              </button>
            </header>
            <div className="flex-1 overflow-auto px-5 py-4">
              <p
                className="text-[12.5px] leading-relaxed"
                style={{ color: "var(--color-text-secondary)" }}
              >
                {sel.excerpt ?? "No excerpt extracted yet. Open the file in a browser to read."}
              </p>
            </div>
          </div>
        ) : (
          <div
            className="flex h-full items-center justify-center text-[13px]"
            style={{ color: "var(--color-text-tertiary)" }}
          >
            Select a newsletter on the left to read.
          </div>
        )}
      </div>
    </div>
  );
}
