import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { openPath } from "@tauri-apps/plugin-opener";

// News tab — lists the HTML newsletters generated in
// ~/.ultron/cockpit/news/. Each newsletter is a full-page artifact, so
// the tab itself just gives a list, summary, and "open in browser" /
// "open in viewer" actions. Inline preview shows the title + first
// paragraphs; the real read happens in a system browser.

export type NewsEntry = {
  filename: string;
  path: string;
  generated_at: string | null;
  size_bytes: number;
  title: string | null;
  excerpt: string | null;
};

function formatBytes(b: number): string {
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1024 / 1024).toFixed(2)} MB`;
}

function dateFromName(name: string): string | null {
  // Names look like newsletter-2026-05-11.html — we surface the date.
  const m = name.match(/(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : null;
}

export function News() {
  const [items, setItems] = useState<NewsEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [showGen, setShowGen] = useState(false);
  const [genTheme, setGenTheme] = useState("");
  const [genDays, setGenDays] = useState(3);
  const [info, setInfo] = useState<string | null>(null);
  const [pendingDelete, setPendingDelete] = useState<NewsEntry | null>(null);
  const [deleteBusy, setDeleteBusy] = useState(false);

  // Summary cache lives in localStorage so we don't burn LLM turns each
  // time the user revisits a newsletter. Keyed by absolute path.
  const SUMMARY_KEY = "ultron.cc.news_summaries.v1";
  const [summaries, setSummaries] = useState<Record<string, string>>(() => {
    try {
      const raw = localStorage.getItem(SUMMARY_KEY);
      if (raw) return JSON.parse(raw) as Record<string, string>;
    } catch {}
    return {};
  });
  const [summarizing, setSummarizing] = useState(false);

  async function load() {
    setLoading(true);
    try {
      const list = await invoke<NewsEntry[]>("list_news");
      setItems(list);
      setSelected((prev) => prev ?? list[0]?.path ?? null);
      setError(null);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  async function summarize(path: string) {
    if (summaries[path] || summarizing) return;
    setSummarizing(true);
    setError(null);
    try {
      const r = (await invoke("summarize_news", { path })) as string;
      const next = { ...summaries, [path]: r };
      setSummaries(next);
      try {
        localStorage.setItem(SUMMARY_KEY, JSON.stringify(next));
      } catch {}
    } catch (e) {
      setError(String(e));
    } finally {
      setSummarizing(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function generate() {
    setGenerating(true);
    setError(null);
    setInfo(null);
    try {
      const r = (await invoke("generate_news", {
        theme: genTheme.trim() || null,
        days: genDays,
      })) as { success: boolean; path: string | null; stderr: string };
      if (!r.success) {
        setError(r.stderr || "news_html_generator failed");
      } else {
        setInfo(r.path ? `Newsletter generada: ${r.path}` : "Newsletter generada.");
        setShowGen(false);
        setGenTheme("");
        await load();
        if (r.path) setSelected(r.path);
      }
    } catch (e) {
      setError(String(e));
    } finally {
      setGenerating(false);
    }
  }

  async function confirmDelete() {
    if (!pendingDelete) return;
    setDeleteBusy(true);
    setError(null);
    try {
      await invoke("delete_news", { path: pendingDelete.path });
      const wasSelected = selected === pendingDelete.path;
      setPendingDelete(null);
      await load();
      if (wasSelected) setSelected(null);
    } catch (e) {
      setError(String(e));
    } finally {
      setDeleteBusy(false);
    }
  }

  function openExternalPath(p: string) {
    openPath(p).catch((e: unknown) => setError(String(e)));
  }

  const sel = items.find((i) => i.path === selected) ?? null;

  return (
    <div className="flex h-full">
      <div
        className="flex w-[44%] min-w-[420px] flex-col overflow-hidden border-r"
        style={{ borderColor: "var(--color-border)" }}
      >
        <header className="border-b px-5 py-4" style={{ borderColor: "var(--color-border)" }}>
          <div className="flex items-baseline justify-between gap-2">
            <div>
              <h1 className="text-[18px] font-semibold leading-tight">News</h1>
              <p className="mt-1 text-[12px]" style={{ color: "var(--color-text-secondary)" }}>
                {items.length} newsletter{items.length === 1 ? "" : "s"} generated by ULTRON Times
              </p>
            </div>
            <button
              type="button"
              onClick={() => setShowGen(!showGen)}
              className="rounded px-2.5 py-1 text-[11.5px] font-medium transition-colors"
              style={{
                background: showGen ? "var(--color-surface-3)" : "var(--color-accent)",
                color: showGen ? "var(--color-text)" : "var(--color-accent-text)",
                border: showGen ? "1px solid var(--color-border-strong)" : "none",
              }}
              title="Genera una newsletter nueva con Gemini"
            >
              {showGen ? "Close" : "Generate"}
            </button>
          </div>
          {showGen && (
            <div
              className="mt-3 rounded p-3"
              style={{
                background: "var(--color-surface-2)",
                border: "1px solid var(--color-border-strong)",
              }}
            >
              <div className="flex flex-wrap items-center gap-2">
                <label
                  className="text-[10px] uppercase tracking-wide"
                  style={{ color: "var(--color-text-tertiary)" }}
                >
                  Days
                </label>
                <input
                  type="number"
                  min={1}
                  max={14}
                  value={genDays}
                  onChange={(e) =>
                    setGenDays(Math.max(1, Math.min(14, parseInt(e.target.value, 10) || 1)))
                  }
                  className="w-14 rounded px-1.5 py-0.5 text-[12px] tabular-nums"
                  style={{
                    background: "var(--color-surface-1)",
                    color: "var(--color-text)",
                    border: "1px solid var(--color-border-strong)",
                    outline: "none",
                  }}
                />
                <label
                  className="text-[10px] uppercase tracking-wide"
                  style={{ color: "var(--color-text-tertiary)" }}
                >
                  Theme
                </label>
                <input
                  type="text"
                  value={genTheme}
                  onChange={(e) => setGenTheme(e.target.value)}
                  placeholder="(opcional)"
                  maxLength={200}
                  className="flex-1 rounded px-2 py-0.5 text-[12px]"
                  style={{
                    background: "var(--color-surface-1)",
                    color: "var(--color-text)",
                    border: "1px solid var(--color-border-strong)",
                    outline: "none",
                    minWidth: 140,
                  }}
                />
              </div>
              <div className="mt-2 flex items-center justify-end gap-2">
                <button
                  type="button"
                  onClick={async () => {
                    setGenerating(true);
                    setError(null);
                    setInfo(null);
                    try {
                      const r = (await invoke("generate_news_session", {
                        theme: genTheme.trim() || null,
                        days: genDays,
                      })) as { success: boolean; stdout: string; stderr: string };
                      if (!r.success) {
                        setError(r.stderr || "session generator failed");
                      } else {
                        setInfo("Gemini session abierta en wt.exe. El prompt está en tu clipboard — pulsa Ctrl+V allí.");
                        setShowGen(false);
                        setGenTheme("");
                      }
                    } catch (e) {
                      setError(String(e));
                    } finally {
                      setGenerating(false);
                    }
                  }}
                  disabled={generating}
                  className="rounded px-3 py-1 text-[12px] font-medium disabled:opacity-50"
                  style={{
                    background: "var(--color-accent)",
                    color: "var(--color-accent-text)",
                  }}
                  title="Recommended: copia prompt al clipboard + abre Gemini wt.exe para que tu pegues"
                >
                  {generating ? "Spawning Gemini..." : "Open Gemini session"}
                </button>
                <button
                  type="button"
                  onClick={generate}
                  disabled={generating}
                  className="rounded px-3 py-1 text-[12px] transition-colors disabled:opacity-50"
                  style={{
                    background: "var(--color-surface-3)",
                    color: "var(--color-text-secondary)",
                    border: "1px solid var(--color-border-strong)",
                  }}
                  title="Modo headless (puede fallar si la CLI no acepta el prompt)"
                >
                  Headless attempt
                </button>
              </div>
              <p
                className="mt-2 text-[10.5px]"
                style={{ color: "var(--color-text-tertiary)" }}
              >
                Llama a news_html_generator.py via uv. Lee el template + skill
                news-publisher y manda el prompt a Gemini CLI; la respuesta
                aterriza en cockpit/news/. Puede tardar 30s-2min.
              </p>
            </div>
          )}
          {info && (
            <div
              className="mt-2 rounded p-2 text-[11.5px]"
              style={{
                background: "rgba(63, 185, 80, 0.08)",
                border: "1px solid rgba(63, 185, 80, 0.22)",
                color: "var(--color-success)",
              }}
            >
              {info}
            </div>
          )}
        </header>
        <div className="flex-1 overflow-auto p-2">
          {loading && (
            <div className="px-3 py-4 text-[12px]" style={{ color: "var(--color-text-tertiary)" }}>
              Loading…
            </div>
          )}
          {error && (
            <div
              className="m-2 rounded p-3 text-[12px]"
              style={{
                background: "rgba(248, 81, 73, 0.06)",
                border: "1px solid rgba(248, 81, 73, 0.22)",
                color: "var(--color-danger)",
              }}
            >
              {error}
            </div>
          )}
          {!loading && items.length === 0 && (
            <div
              className="m-2 rounded p-6 text-center text-[12.5px]"
              style={{
                background: "var(--color-surface-2)",
                border: "1px solid var(--color-border)",
                color: "var(--color-text-secondary)",
              }}
            >
              No newsletters yet. Run the news pipeline to generate one.
            </div>
          )}
          {items.map((n) => {
            const active = selected === n.path;
            const date = dateFromName(n.filename);
            return (
              <button
                key={n.path}
                type="button"
                onClick={() => setSelected(n.path)}
                className="block w-full rounded px-3 py-2 text-left transition-colors"
                style={{
                  background: active ? "var(--color-surface-3)" : "transparent",
                  border: `1px solid ${active ? "var(--color-border-strong)" : "transparent"}`,
                }}
              >
                <div className="flex items-baseline gap-2">
                  <span
                    className="text-[12.5px] font-medium"
                    style={{ color: "var(--color-text)" }}
                  >
                    {n.title ?? n.filename}
                  </span>
                  <span
                    className="ml-auto text-[10.5px] tabular-nums"
                    style={{ color: "var(--color-text-tertiary)" }}
                  >
                    {date ?? n.generated_at ?? ""}
                  </span>
                </div>
                {n.excerpt && (
                  <div
                    className="mt-1 truncate text-[11.5px]"
                    style={{ color: "var(--color-text-tertiary)" }}
                  >
                    {n.excerpt}
                  </div>
                )}
                <div
                  className="mt-1 text-[10.5px]"
                  style={{ color: "var(--color-text-faint)" }}
                >
                  {formatBytes(n.size_bytes)}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      <div className="flex-1 overflow-hidden">
        {sel ? (
          <div className="flex h-full flex-col overflow-hidden">
            <header
              className="flex items-center justify-between border-b px-5 py-4"
              style={{ borderColor: "var(--color-border)" }}
            >
              <div className="min-w-0">
                <h2 className="truncate text-[15px] font-semibold">
                  {sel.title ?? sel.filename}
                </h2>
                <div
                  className="mt-1 truncate text-[10.5px]"
                  style={{ fontFamily: "var(--font-mono)", color: "var(--color-text-faint)" }}
                  title={sel.path}
                >
                  {sel.path}
                </div>
              </div>
              <div className="flex shrink-0 gap-2">
                <button
                  type="button"
                  onClick={() => setPendingDelete(sel)}
                  className="rounded px-3 py-1.5 text-[12px] transition-colors"
                  style={{
                    background: "var(--color-surface-2)",
                    color: "var(--color-danger)",
                    border: "1px solid rgba(248, 81, 73, 0.32)",
                  }}
                  title="Delete this newsletter HTML file"
                >
                  Delete
                </button>
                <button
                  type="button"
                  onClick={() => openExternalPath(sel.path)}
                  className="rounded px-3 py-1.5 text-[12px] font-medium transition-colors"
                  style={{
                    background: "var(--color-accent)",
                    color: "var(--color-accent-text)",
                  }}
                >
                  Open in browser
                </button>
              </div>
            </header>
            <div className="flex-1 overflow-auto px-5 py-4">
              <p
                className="text-[12px] leading-relaxed"
                style={{ color: "var(--color-text-tertiary)" }}
              >
                {sel.excerpt ?? "No excerpt extracted yet. Open the file in a browser to read."}
              </p>

              <div
                className="mt-5 flex items-baseline justify-between gap-2 border-t pt-3"
                style={{ borderColor: "var(--color-border)" }}
              >
                <h3 className="text-[11px] font-medium uppercase tracking-[0.06em]"
                  style={{ color: "var(--color-text-secondary)" }}
                >
                  AI summary
                </h3>
                <button
                  type="button"
                  onClick={() => summarize(sel.path)}
                  disabled={summarizing || !!summaries[sel.path]}
                  className="rounded px-2.5 py-1 text-[11px] font-medium transition-colors disabled:opacity-40"
                  style={{
                    background: summaries[sel.path]
                      ? "var(--color-surface-2)"
                      : "var(--color-accent)",
                    color: summaries[sel.path]
                      ? "var(--color-text-tertiary)"
                      : "var(--color-accent-text)",
                    border: summaries[sel.path]
                      ? "1px solid var(--color-border)"
                      : "none",
                  }}
                  title={
                    summaries[sel.path]
                      ? "Already summarised (cached)"
                      : "Resume con Claude (6 bullets + conclusion)"
                  }
                >
                  {summarizing
                    ? "Summarising..."
                    : summaries[sel.path]
                      ? "Cached"
                      : "Summarise"}
                </button>
              </div>
              {summaries[sel.path] ? (
                <pre
                  className="mt-2 text-[12.5px] leading-relaxed"
                  style={{
                    color: "var(--color-text-secondary)",
                    whiteSpace: "pre-wrap",
                    fontFamily: "inherit",
                  }}
                >
                  {summaries[sel.path]}
                </pre>
              ) : (
                <p
                  className="mt-2 text-[11.5px]"
                  style={{ color: "var(--color-text-faint)" }}
                >
                  Pulsa Summarise para que Claude resuma esta newsletter en 6
                  bullets. El resumen se cachea local para no gastar turnos al
                  revisitarla.
                </p>
              )}
            </div>
          </div>
        ) : (
          <div
            className="flex h-full items-center justify-center text-[13px]"
            style={{ color: "var(--color-text-tertiary)" }}
          >
            Select a newsletter on the left to read.
          </div>
        )}
      </div>

      {pendingDelete && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center px-6"
          style={{ background: "rgba(0,0,0,0.55)" }}
          onClick={() => !deleteBusy && setPendingDelete(null)}
        >
          <div
            className="w-full max-w-[440px] rounded p-5"
            style={{
              background: "var(--color-surface-1)",
              border: "1px solid var(--color-border-strong)",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="text-[14px] font-semibold">Delete newsletter</h3>
            <p
              className="mt-2 text-[12.5px] leading-relaxed"
              style={{ color: "var(--color-text-secondary)" }}
            >
              Borrar el archivo HTML <b>{pendingDelete.filename}</b>? El
              borrado es permanente — usa git para recuperar si lo
              necesitas.
            </p>
            <div className="mt-4 flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => setPendingDelete(null)}
                disabled={deleteBusy}
                className="rounded px-3 py-1.5 text-[12px]"
                style={{
                  background: "transparent",
                  color: "var(--color-text-tertiary)",
                  border: "1px solid var(--color-border-strong)",
                }}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={confirmDelete}
                disabled={deleteBusy}
                className="rounded px-3 py-1.5 text-[12px] font-medium"
                style={{
                  background: "var(--color-danger)",
                  color: "#fff",
                }}
              >
                {deleteBusy ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
