// skills/mod.rs — ULTRON Control Center skills domain.
//
// Single source of truth: ~/.ultron/skills/registry.json. That file is
// regenerated by `skill_vault.py registry` on every Stop hook, so it stays
// in sync with the real filesystem state. Frontend just reads it.
//
// Schema (v2):
//   { "schema_version": 2, "generated_at": "...", "counts": {...},
//     "skills": [{name, state, source, path, description, tags,
//                 usage_count, embedding_id, ...}] }
//
// State values: "active" | "plugin" | "vaulted"
//   active   → ~/.claude/skills/<name>/SKILL.md
//   plugin   → installed as Claude Code plugin
//   vaulted  → ~/.ultron/skill-vault/<name>/SKILL.md
//
// Groups:
//   types    — All public and internal types for the skills domain
//   registry — Registry-file reading and SKILL.md preview
//   crud     — Create / update / delete on skill directories
//   hash     — SHA1 + date helpers (reused by agents.rs)
//   origin   — Origin-aware listing, toggle, and bulk-toggle

pub(crate) mod crud;
pub(crate) mod origin;
pub(crate) mod registry;
#[cfg(test)]
mod tests;
pub(crate) mod types;

// ---------------------------------------------------------------------------
// Re-exports — preserve the flat public API that crate::skills callers expect.
// ---------------------------------------------------------------------------

pub use crud::update_skill_md_inner;
pub use origin::{
    list_skills_with_origin_inner, plugin_command_entries, skill_toggle_inner,
    skills_bulk_toggle_inner,
};
pub use registry::list_skills_inner;
pub use types::{BulkToggleResult, SkillEntry, SkillInfo, SkillUpdateResult};
