// skills/registry.rs — Registry-file reading and SKILL.md preview.
//
// Single source of truth: ~/.ultron/skills/registry.json.
// That file is regenerated by `skill_vault.py registry` on every Stop hook.

use std::fs;
use std::path::PathBuf;

use super::types::{RegistryRoot, SkillInfo};

pub(crate) fn registry_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".ultron/skills/registry.json"))
}

/// Strip non-Latin characters (CJK, Cyrillic, Hebrew, Arabic, …) from a
/// string while preserving ASCII + Latin Extended (so Spanish accents
/// like á é í ó ú ñ are kept). Collapses leftover whitespace and orphan
/// punctuation introduced by the strip.
pub(crate) fn strip_non_latin(s: &str) -> String {
    let replaced: String = s
        .chars()
        .map(|c| {
            let cp = c as u32;
            // ASCII (0x00–0x7F), Latin-1 Supplement + Latin Extended-A + B
            // (0xC0–0x24F), plus a few Latin Extended Additional (0x1E00–0x1EFF).
            if cp < 0x80 || (0xC0..=0x24F).contains(&cp) || (0x1E00..=0x1EFF).contains(&cp) {
                c
            } else {
                ' '
            }
        })
        .collect();

    // Collapse double spaces and orphan punctuation that the strip leaves
    // behind (e.g. "research, 研究, deep" → "research,  , deep" → "research, deep").
    let mut out = replaced;
    // Iterative cleanup with a hard cap so a pathological input can never spin.
    for _ in 0..6 {
        let before = out.len();
        out = out.replace("  ", " ");
        out = out.replace(" ,", ",");
        out = out.replace(",,", ",");
        if out.len() == before {
            break;
        }
    }
    // Restore a single space after each comma for readability.
    out = out.replace(",", ", ");
    // Final whitespace collapse (bounded — no while).
    while out.contains("  ") {
        out = out.replace("  ", " ");
    }
    out.trim_matches(|c: char| c == ',' || c.is_whitespace())
        .to_string()
}

pub fn list_skills_inner() -> Result<Vec<SkillInfo>, String> {
    let path = registry_path().ok_or_else(|| "no HOME".to_string())?;
    let raw = fs::read_to_string(&path)
        .map_err(|e| format!("read registry.json: {} ({})", e, path.display()))?;
    let root: RegistryRoot =
        serde_json::from_str(&raw).map_err(|e| format!("parse registry.json: {}", e))?;

    let mut out: Vec<SkillInfo> = Vec::with_capacity(root.skills.len());
    for (key, s) in root.skills.into_iter() {
        // Prefer the explicit "name" field; fall back to the suffix of the
        // composite key ("active::foo" → "foo") when missing.
        let name = match s.name {
            Some(n) => n,
            None => key.split("::").nth(1).unwrap_or(&key).to_string(),
        };
        let cleaned_desc = s.description.map(|d| strip_non_latin(&d));
        let cleaned_tags: Vec<String> = s
            .tags
            .into_iter()
            .map(|t| strip_non_latin(&t))
            .filter(|t| !t.is_empty())
            .collect();
        // Clamp to 1..=10; absent → 5 (mid-range default).
        let priority = s.priority.map(|p| p.clamp(1, 10)).unwrap_or(5);
        out.push(SkillInfo {
            name,
            state: s.state.unwrap_or_else(|| "unknown".to_string()),
            source: s.source,
            description: cleaned_desc.filter(|d| !d.is_empty()),
            tags: cleaned_tags,
            path: s.path,
            usage_count: s.usage_count,
            priority,
            security: s.security,
        });
    }
    // Sort by priority descending so the frontend and any caller that needs
    // deterministic conflict resolution between same-trigger skills always
    // receives the highest-priority skill first.
    out.sort_by(|a, b| b.priority.cmp(&a.priority).then(a.name.cmp(&b.name)));
    Ok(out)
}

// NOTE: read_skill_md_inner (SKILL.md preview) se retiró 2026-08-11 junto a su
// comando huérfano (audit 08-09 #38); read_skill_md_inner_raw ya cayó en v15.3.6.
