#!/usr/bin/env python3
"""
ULTRON v10.0 Cockpit - IDE launcher.

Usage:
    python launch_project.py <project_id> [--ide <override>] [--no-context]
    python launch_project.py --list
    python launch_project.py --search <query>

Reads projects.json, finds the project, opens it in the configured IDE.
Optionally writes a `.claude/context.md` pre-fill so the next Claude session
in that project starts warm.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, str(Path(__file__).parent))
from cockpit_base import Cockpit, PROJECTS_JSON  # noqa: E402


# IDE -> launcher command (None = will probe via shutil.which)
IDE_LAUNCHERS = {
    "Rider":          ["rider64.exe", "rider"],
    "Webstorm":       ["webstorm64.exe", "webstorm"],
    "VSCode":         ["code"],
    "Cursor":         ["cursor"],
    "AndroidStudio":  ["studio64.exe", "studio"],
    "VisualStudio":   ["devenv.exe", "devenv"],
    "CLion":          ["clion64.exe", "clion"],
    "PyCharm":        ["pycharm64.exe", "pycharm"],
    "UnityHub":       ["Unity Hub.exe", "unityhub"],
    "Xcode":          [],  # macOS only, will fail gracefully
}

# Unity Hub hardcoded search paths (Windows)
UNITY_HUB_PATHS = [
    Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Unity Hub" / "Unity Hub.exe",
    Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Unity Hub" / "Unity Hub.exe",
]


def find_launcher(ide_label: str) -> str | None:
    candidates = IDE_LAUNCHERS.get(ide_label, [])
    for c in candidates:
        path = shutil.which(c)
        if path:
            return path
    # Unity Hub: check hardcoded install paths
    if ide_label == "UnityHub":
        for hub_path in UNITY_HUB_PATHS:
            if hub_path.exists():
                return str(hub_path)
    # Fallback to JetBrains Toolbox common locations
    if ide_label in ("Rider", "Webstorm", "CLion", "AndroidStudio", "PyCharm"):
        toolbox = Path(os.environ.get("LOCALAPPDATA", "")) / "JetBrains" / "Toolbox" / "scripts"
        for c in candidates:
            cand = toolbox / c
            if cand.exists():
                return str(cand)
    return None


def resolve_ide(project: dict) -> str:
    """Auto-detect IDE when not explicitly set, or validate the configured one.
    Rule: engine=Unity or (language=C# and type=game) → UnityHub.
    Rule: engine=UE5/Unreal or (language=C++ and type=game) → Rider.
    """
    ide = project.get("ide") or "VSCode"
    engine = (project.get("engine") or "").lower()
    lang = (project.get("language") or "").lower()
    ptype = (project.get("type") or "").lower()
    if engine == "unity" or (lang == "c#" and ptype == "game"):
        return "UnityHub"
    if engine in ("ue5", "unreal") or (lang == "c++" and ptype == "game"):
        return "Rider"
    return ide


def load_projects() -> list[dict]:
    data = Cockpit.read_json(PROJECTS_JSON, default={"projects": []})
    return data.get("projects", [])


def find_project(query: str, projects: list[dict]) -> dict | None:
    """Find by exact id, or by case-insensitive substring of name/id."""
    q = query.lower()
    # Exact id match first
    for p in projects:
        if p.get("id") == query:
            return p
    # Substring match on name or id
    matches = [p for p in projects
               if q in p.get("id", "").lower() or q in p.get("name", "").lower()]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        print(f"[launcher] Ambiguous query '{query}', candidates:")
        for m in matches[:10]:
            print(f"  {m['id']:<28} {m['name']}")
        return None
    return None


def write_context_prefill(project: dict) -> None:
    """Drop a .claude/context.md inside the project so next Claude session warm-starts."""
    proj_path = Path(project["path"])
    if not proj_path.exists():
        return
    context_dir = proj_path / ".claude"
    context_dir.mkdir(exist_ok=True)
    context_file = context_dir / "context.md"

    # Idempotent: overwrite is fine, this is regenerable
    last_active = project.get("last_active") or "(unknown)"
    deadline = project.get("deadline") or "(none)"
    tags = ", ".join(project.get("tags", []))

    content = f"""# Project context (auto-generated by ULTRON Cockpit)
> Generated: {datetime.now().isoformat(timespec='seconds')}
> Project: {project['name']} ({project['id']})

## Snapshot

- **Path:** `{project['path']}`
- **IDE:** {project.get('ide', '?')}
- **Language:** {project.get('language', '?')}
- **Type:** {project.get('type', '?')}
- **Last active:** {last_active}
- **Deadline:** {deadline}
- **Status:** {project.get('status', '?')}
- **Tags:** {tags}

## Hint to Claude
This is a warm-start context. Read PROJECT.md / README.md if they exist for
deeper context. Last 5 commits via `git log --oneline -5`.
"""
    context_file.write_text(content, encoding="utf-8")


def log_launch(project_id: str) -> None:
    pass  # legacy stub — activity tracking retired


def _spawn_ai_session(cli: str, project_id: str, proj_path: Path) -> None:
    """Best-effort spawn of an AI CLI session (claude or codex) in a new
    Windows Terminal tab at the project's cwd.

    Falls back to a bare Popen (no terminal wrapper) if wt.exe is not
    available.  Errors are non-fatal — the IDE has already opened.
    """
    wt = shutil.which("wt.exe") or shutil.which("wt")
    title = "ULTRON · " + project_id + " · " + cli
    path_str = str(proj_path)
    try:
        cli_args = [cli]
        if cli == "claude":
            cli_args.append("--dangerously-skip-permissions")
        if wt:
            cmd = [wt, "new-tab", "--title", title, "-d", path_str] + cli_args
            subprocess.Popen(cmd,
                             creationflags=subprocess.CREATE_NEW_PROCESS_GROUP
                             if os.name == "nt" else 0)
            print(f"[launcher] spawned {cli} in new WT tab (cwd={path_str})")
        else:
            subprocess.Popen(cli_args,
                             cwd=path_str,
                             creationflags=subprocess.CREATE_NEW_PROCESS_GROUP
                             if os.name == "nt" else 0)
            print(f"[launcher] spawned {cli} (no wt.exe, cwd={path_str})")
    except Exception as e:
        print(f"[launcher] WARN: with-{cli} failed: {e}")


def inject_notes_into_context(project: dict) -> None:
    """Append last 5 project notes to .claude/context.md without clobbering existing content."""
    notes_script = Path(__file__).parent / "project_notes.py"
    if not notes_script.exists():
        return
    try:
        r = subprocess.run(
            [sys.executable, str(notes_script), "export", project["id"], "--n", "5"],
            capture_output=True, text=True, timeout=10, encoding="utf-8",
        )
        notes_block = (r.stdout or "").strip()
        if not notes_block:
            return
        proj_path = Path(project["path"])
        context_file = proj_path / ".claude" / "context.md"
        if not context_file.exists():
            return
        existing = context_file.read_text(encoding="utf-8")
        marker = "\n\n<!-- ultron-notes -->\n"
        # Remove previous notes injection if present (idempotent)
        if marker in existing:
            existing = existing[:existing.index(marker)]
        context_file.write_text(
            existing + marker + notes_block + "\n",
            encoding="utf-8",
        )
        # Show what was injected so the user knows what Claude will see
        note_count = notes_block.count("**") // 2  # each entry has opening + closing **
        print(f"[launcher] injected {note_count} note(s) into context.md:")
        for line in notes_block.splitlines():
            if line.strip():
                print(f"    {line[:100]}")
    except Exception as e:
        print(f"[launcher] WARN: notes inject failed: {e}")


def launch(project: dict, ide_override: str | None = None,
           write_context: bool = True, dry_run: bool = False,
           with_claude: bool = False, with_codex: bool = False,
           resume: bool = False) -> int:
    ide_label = ide_override or resolve_ide(project)
    launcher = find_launcher(ide_label)

    proj_path = Path(project["path"])
    if not proj_path.exists():
        print(f"[launcher] ERROR: project path does not exist: {proj_path}")
        return 2

    if not launcher:
        print(f"[launcher] WARNING: no launcher found for {ide_label}, falling back to 'code'")
        launcher = shutil.which("code")
        if not launcher:
            print(f"[launcher] ERROR: no IDE launcher available at all")
            return 3

    if write_context:
        try:
            write_context_prefill(project)
        except Exception as e:
            print(f"[launcher] WARN: could not write context.md: {e}")

    if resume:
        try:
            inject_notes_into_context(project)
        except Exception as e:
            print(f"[launcher] WARN: resume notes inject failed: {e}")

    print(f"[launcher] Opening {project['name']} ({project['id']}) in {ide_label}")
    print(f"           Path: {proj_path}")
    print(f"           Launcher: {launcher}")

    if dry_run:
        print("[launcher] dry-run, not actually launching")
        return 0

    log_launch(project["id"])

    try:
        # Unity Hub opens projects with "--" separator before project flags
        if ide_label == "UnityHub":
            cmd = [launcher, "--", "--open", str(proj_path)]
        else:
            cmd = [launcher, str(proj_path)]
        subprocess.Popen(cmd,
                         creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if os.name == "nt" else 0)
    except Exception as e:
        print(f"[launcher] ERROR launching: {e}")
        return 4

    # v10.6.2: launch extra apps + open links if configured on the project.
    # Errors here are non-fatal (the IDE already opened — that's the main goal).
    extra_apps = project.get("apps") or []
    for app_name in extra_apps:
        _launch_extra_app(app_name)
    links = project.get("links") or {}
    if links:
        try:
            import webbrowser
            for label, url in links.items():
                webbrowser.open(url)
                print(f"[launcher] opened link [{label}]: {url}")
        except Exception as e:
            print(f"[launcher] WARN: link open failed: {e}")

    # v10.7: optional AI session tabs in Windows Terminal at the project cwd.
    # Non-fatal: the IDE is already open; errors here must not change exit code.
    if with_claude:
        _spawn_ai_session("claude", project["id"], proj_path)
    if with_codex:
        _spawn_ai_session("codex", project["id"], proj_path)

    return 0


def _launch_extra_app(name: str) -> None:
    """Best-effort launch of an extra app declared on a project.
    Resolution order:
      1. Absolute path → Popen directly
      2. Name in apps.json → use apps_launcher.py
      3. shutil.which → Popen
    """
    target = name.strip()
    try:
        if Path(target).is_file() and Path(target).is_absolute():
            subprocess.Popen([target],
                             creationflags=subprocess.CREATE_NEW_PROCESS_GROUP
                             if os.name == "nt" else 0)
            print(f"[launcher] spawned extra app (path): {target}")
            return
        # Try apps_launcher
        apps_script = Path(__file__).parent / "apps_launcher.py"
        if apps_script.exists():
            r = subprocess.run([sys.executable, str(apps_script), target],
                               capture_output=True, text=True, timeout=10,
                               encoding="utf-8", errors="replace")
            if r.returncode == 0:
                print(f"[launcher] spawned extra app (apps.json): {target}")
                return
        # Last resort: PATH lookup
        resolved = shutil.which(target)
        if resolved:
            subprocess.Popen([resolved],
                             creationflags=subprocess.CREATE_NEW_PROCESS_GROUP
                             if os.name == "nt" else 0)
            print(f"[launcher] spawned extra app (PATH): {resolved}")
            return
        print(f"[launcher] WARN: could not resolve extra app '{target}'")
    except Exception as e:
        print(f"[launcher] WARN: extra app '{target}' failed: {e}")


def main():
    p = argparse.ArgumentParser(description="ULTRON Cockpit IDE launcher")
    p.add_argument("query", nargs="?", help="project id (or substring)")
    p.add_argument("--list", action="store_true", help="list all active projects")
    p.add_argument("--search", help="search by substring without launching")
    p.add_argument("--ide", help="override IDE (e.g. VSCode)")
    p.add_argument("--no-context", action="store_true", help="skip writing .claude/context.md")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--with-claude", action="store_true",
                   help="spawn a Claude session in a new WT tab at the project cwd")
    p.add_argument("--with-codex", action="store_true",
                   help="spawn a Codex session in a new WT tab at the project cwd")
    p.add_argument("--resume", action="store_true",
                   help="inject last 5 notes into .claude/context.md before launching")
    args = p.parse_args()

    projects = load_projects()
    if not projects:
        print("[launcher] No projects registered. Run: python scan_projects.py")
        return 1

    if args.list:
        active = [p for p in projects if p.get("status") in ("active", "auto-detected", "manual")]
        active.sort(key=lambda p: (p.get("last_active") or "0000"), reverse=True)
        print(f"[launcher] {len(active)} active projects:\n")
        for p in active[:30]:
            print(f"  {p['id']:<32} {p.get('ide','?'):<14} {p.get('last_active','?')} {p['name']}")
        return 0

    if args.search:
        matches = [p for p in projects
                   if args.search.lower() in p.get("id","").lower()
                   or args.search.lower() in p.get("name","").lower()]
        for m in matches[:20]:
            print(f"  {m['id']:<32} {m.get('ide','?'):<14} {m['name']}")
        return 0

    if not args.query:
        p.print_help()
        return 1

    proj = find_project(args.query, projects)
    if not proj:
        print(f"[launcher] No match for '{args.query}'. Try --search or --list")
        return 1

    return launch(proj,
                  ide_override=args.ide,
                  write_context=not args.no_context,
                  dry_run=args.dry_run,
                  with_claude=args.with_claude,
                  with_codex=args.with_codex,
                  resume=args.resume)


if __name__ == "__main__":
    sys.exit(main())
