// ULTRON Control Center 2.0 - Workdays domain (auto-generated by sprint 2026-05-25)
use serde::{Deserialize, Serialize};
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

fn new_id(prefix: &str) -> String {
    static C: AtomicU64 = AtomicU64::new(0);
    let n = C.fetch_add(1, Ordering::Relaxed);
    let t = SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_micros()).unwrap_or(0);
    format!("{prefix}-{t}-{n}")
}
fn now_iso() -> String {
    let s = SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0);
    format!("epoch:{}", s)
}
fn today_date() -> String { chrono::Local::now().format("%Y-%m-%d").to_string() }

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum WorkdayStatus { Planned, InProgress, Paused, Completed, Archived }
impl std::fmt::Display for WorkdayStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            WorkdayStatus::Planned => write!(f, "planned"),
            WorkdayStatus::InProgress => write!(f, "in_progress"),
            WorkdayStatus::Paused => write!(f, "paused"),
            WorkdayStatus::Completed => write!(f, "completed"),
            WorkdayStatus::Archived => write!(f, "archived"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "snake_case")]
pub enum GoalStatus { #[default] Pending, Done, Skipped }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkdayGoal { pub id: String, pub text: String, #[serde(default)] pub status: GoalStatus }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Workday {
    pub id: String,
    #[serde(default)] pub template_id: Option<String>,
    pub title: String,
    pub status: WorkdayStatus,
    pub planned_date: String,
    #[serde(default)] pub start_ts: Option<String>,
    #[serde(default)] pub end_ts: Option<String>,
    #[serde(default)] pub focus_seconds: u64,
    #[serde(default)] pub break_seconds: u64,
    #[serde(default)] pub energy_before: Option<u8>,
    #[serde(default)] pub energy_after: Option<u8>,
    #[serde(default)] pub mood_note: Option<String>,
    #[serde(default)] pub retro_good: Option<String>,
    #[serde(default)] pub retro_bad: Option<String>,
    #[serde(default)] pub retro_learned: Option<String>,
    #[serde(default)] pub summary_md: Option<String>,
    #[serde(default)] pub goals: Vec<WorkdayGoal>,
    #[serde(default)] pub linked_sessions: Vec<String>,
    #[serde(default)] pub linked_tasks: Vec<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkdayTemplate {
    pub id: String, pub name: String,
    #[serde(default)] pub default_title: Option<String>,
    #[serde(default)] pub default_goals: Vec<String>,
    #[serde(default)] pub notes: Option<String>,
    pub created_at: String, pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct WorkdayMetrics {
    pub id: String, pub title: String, pub status: WorkdayStatus, pub planned_date: String,
    pub focus_minutes: u64, pub break_minutes: u64,
    pub total_goals: usize, pub completed_goals: usize,
    pub linked_sessions: usize, pub linked_tasks: usize,
}

pub fn workdays_dir() -> Result<PathBuf, String> {
    Ok(dirs::home_dir().ok_or_else(|| "no home".to_string())?.join(".ultron").join("cockpit").join("workdays"))
}
fn templates_dir() -> Result<PathBuf, String> {
    Ok(dirs::home_dir().ok_or_else(|| "no home".to_string())?.join(".ultron").join("cockpit").join("workday-templates"))
}
fn workday_path(id: &str) -> Result<PathBuf, String> { Ok(workdays_dir()?.join(format!("{id}.json"))) }
fn template_path(id: &str) -> Result<PathBuf, String> { Ok(templates_dir()?.join(format!("{id}.json"))) }

fn atomic_write(path: &PathBuf, j: &str) -> Result<(), String> {
    if let Some(p) = path.parent() { fs::create_dir_all(p).map_err(|e| format!("mkdir: {e}"))?; }
    let tmp = path.with_extension("json.tmp");
    { let mut f = fs::File::create(&tmp).map_err(|e| format!("create: {e}"))?;
      f.write_all(j.as_bytes()).map_err(|e| format!("write: {e}"))?; f.sync_all().ok(); }
    fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))
}
fn persist_workday(wd: &Workday) -> Result<(), String> {
    let p = workday_path(&wd.id)?;
    atomic_write(&p, &serde_json::to_string_pretty(wd).map_err(|e| format!("ser: {e}"))?)
}
fn load_from_path(p: &PathBuf) -> Result<Workday, String> {
    serde_json::from_str(&fs::read_to_string(p).map_err(|e| format!("read: {e}"))?).map_err(|e| format!("parse: {e}"))
}
fn load_wd(id: &str) -> Result<Workday, String> {
    let p = workday_path(id)?;
    if !p.exists() { return Err(format!("workday {id} not found")); }
    load_from_path(&p)
}
fn persist_template(t: &WorkdayTemplate) -> Result<(), String> {
    let p = template_path(&t.id)?;
    atomic_write(&p, &serde_json::to_string_pretty(t).map_err(|e| format!("ser: {e}"))?)
}

fn assert_transition(from: &WorkdayStatus, to: &WorkdayStatus) -> Result<(), String> {
    let ok = matches!((from, to),
        (WorkdayStatus::Planned, WorkdayStatus::InProgress)
        | (WorkdayStatus::InProgress, WorkdayStatus::Paused)
        | (WorkdayStatus::Paused, WorkdayStatus::InProgress)
        | (WorkdayStatus::InProgress, WorkdayStatus::Completed)
        | (WorkdayStatus::Completed, WorkdayStatus::Archived)
        | (WorkdayStatus::InProgress, WorkdayStatus::Archived)
        | (WorkdayStatus::Paused, WorkdayStatus::Archived));
    if ok { Ok(()) } else { Err(format!("invalid transition: {} -> {}", from, to)) }
}

fn gen_summary(wd: &Workday) -> String {
    let fm = wd.focus_seconds / 60; let bm = wd.break_seconds / 60;
    let tot = wd.goals.len();
    let done = wd.goals.iter().filter(|g| g.status == GoalStatus::Done).count();
    let gl: String = wd.goals.iter().map(|g| {
        let m = match g.status { GoalStatus::Done => "[x]", GoalStatus::Skipped => "[~]", GoalStatus::Pending => "[ ]" };
        format!("- {m} {}\n", g.text)
    }).collect();
    format!("# {}\n\nFecha: {}  \nEstado: {}  \nFoco: {fm} min  \nDescanso: {bm} min  \nTareas: {done}/{tot}  \n\n## Objetivos\n{gl}",
        wd.title, wd.planned_date, wd.status)
}

pub fn create_workday_inner(title: String, planned_date: Option<String>, template_id: Option<String>, goals: Option<Vec<String>>) -> Result<Workday, String> {
    let d = planned_date.unwrap_or_else(today_date);
    let gi: Vec<WorkdayGoal> = goals.unwrap_or_default().into_iter()
        .map(|text| WorkdayGoal { id: new_id("goal"), text, status: GoalStatus::Pending }).collect();
    let wd = Workday { id: new_id("wd"), template_id, title, status: WorkdayStatus::Planned, planned_date: d,
        start_ts: None, end_ts: None, focus_seconds: 0, break_seconds: 0,
        energy_before: None, energy_after: None, mood_note: None,
        retro_good: None, retro_bad: None, retro_learned: None, summary_md: None,
        goals: gi, linked_sessions: Vec::new(), linked_tasks: Vec::new(), created_at: now_iso() };
    persist_workday(&wd)?; Ok(wd)
}
pub fn start_workday_inner(id: String, energy_before: Option<u8>) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    assert_transition(&wd.status, &WorkdayStatus::InProgress)?;
    wd.status = WorkdayStatus::InProgress; wd.start_ts = Some(now_iso());
    if let Some(e) = energy_before { wd.energy_before = Some(e); }
    persist_workday(&wd)?; Ok(wd)
}
pub fn pause_workday_inner(id: String, break_seconds_delta: Option<u64>) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    assert_transition(&wd.status, &WorkdayStatus::Paused)?;
    wd.status = WorkdayStatus::Paused;
    if let Some(d) = break_seconds_delta { wd.break_seconds += d; }
    persist_workday(&wd)?; Ok(wd)
}
pub fn resume_workday_inner(id: String) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    assert_transition(&wd.status, &WorkdayStatus::InProgress)?;
    wd.status = WorkdayStatus::InProgress;
    persist_workday(&wd)?; Ok(wd)
}
pub fn complete_workday_inner(id: String, focus_seconds: Option<u64>, energy_after: Option<u8>, mood_note: Option<String>, retro_good: Option<String>, retro_bad: Option<String>, retro_learned: Option<String>) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    assert_transition(&wd.status, &WorkdayStatus::Completed)?;
    if let Some(s) = focus_seconds { wd.focus_seconds = s; }
    if let Some(e) = energy_after { wd.energy_after = Some(e); }
    if let Some(m) = mood_note { wd.mood_note = Some(m); }
    if let Some(g) = retro_good { wd.retro_good = Some(g); }
    if let Some(b) = retro_bad { wd.retro_bad = Some(b); }
    if let Some(l) = retro_learned { wd.retro_learned = Some(l); }
    wd.status = WorkdayStatus::Completed; wd.end_ts = Some(now_iso());
    let s = gen_summary(&wd); wd.summary_md = Some(s.clone());
    persist_workday(&wd)?;
    let wid = wd.id.clone(); let wt = wd.title.clone(); let wdt = wd.planned_date.clone();
    tauri::async_runtime::spawn(async move {
        let md = serde_json::json!({"source":"workday","workday_id":wid,"title":wt,"date":wdt});
        let _ = crate::mem0::add_inner(s, "workdays".to_string(), Some(md)).await;
    });
    Ok(wd)
}
pub fn archive_workday_inner(id: String) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    assert_transition(&wd.status, &WorkdayStatus::Archived)?;
    wd.status = WorkdayStatus::Archived;
    persist_workday(&wd)?; Ok(wd)
}
pub fn list_workdays_inner(status_filter: Option<String>, date_from: Option<String>, date_to: Option<String>, limit: Option<usize>) -> Result<Vec<Workday>, String> {
    let d = workdays_dir()?;
    if !d.exists() { return Ok(Vec::new()); }
    let es = fs::read_dir(&d).map_err(|e| format!("read: {e}"))?;
    let mut ws: Vec<Workday> = Vec::new();
    for e in es.flatten() {
        let p = e.path();
        if p.extension().and_then(|x| x.to_str()) != Some("json") { continue; }
        if let Ok(wd) = load_from_path(&p) { ws.push(wd); }
    }
    if let Some(ref sf) = status_filter { ws.retain(|wd| wd.status.to_string() == *sf); }
    if let Some(ref f) = date_from { ws.retain(|wd| wd.planned_date >= *f); }
    if let Some(ref t) = date_to { ws.retain(|wd| wd.planned_date <= *t); }
    ws.sort_by(|a, b| b.planned_date.cmp(&a.planned_date));
    if let Some(n) = limit { ws.truncate(n); }
    Ok(ws)
}
pub fn get_workday_detail_inner(id: String) -> Result<Workday, String> { load_wd(&id) }
pub fn link_session_inner(id: String, session_id: String) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    if !wd.linked_sessions.contains(&session_id) { wd.linked_sessions.push(session_id); persist_workday(&wd)?; }
    Ok(wd)
}
pub fn link_task_inner(id: String, task_id: String) -> Result<Workday, String> {
    let mut wd = load_wd(&id)?;
    if !wd.linked_tasks.contains(&task_id) { wd.linked_tasks.push(task_id); persist_workday(&wd)?; }
    Ok(wd)
}
pub fn get_workday_metrics_inner(id: String) -> Result<WorkdayMetrics, String> {
    let wd = load_wd(&id)?;
    Ok(WorkdayMetrics { id: wd.id.clone(), title: wd.title.clone(), status: wd.status.clone(),
        planned_date: wd.planned_date.clone(),
        focus_minutes: wd.focus_seconds/60, break_minutes: wd.break_seconds/60,
        total_goals: wd.goals.len(),
        completed_goals: wd.goals.iter().filter(|g| g.status==GoalStatus::Done).count(),
        linked_sessions: wd.linked_sessions.len(), linked_tasks: wd.linked_tasks.len() })
}
pub fn list_templates_inner() -> Result<Vec<WorkdayTemplate>, String> {
    let d = templates_dir()?;
    if !d.exists() { return Ok(Vec::new()); }
    let es = fs::read_dir(&d).map_err(|e| format!("read: {e}"))?;
    let mut ts: Vec<WorkdayTemplate> = Vec::new();
    for e in es.flatten() {
        let p = e.path();
        if p.extension().and_then(|x| x.to_str()) != Some("json") { continue; }
        if let Ok(r) = fs::read_to_string(&p) {
            if let Ok(t) = serde_json::from_str::<WorkdayTemplate>(&r) { ts.push(t); }
        }
    }
    ts.sort_by(|a, b| b.created_at.cmp(&a.created_at));
    Ok(ts)
}
pub fn save_template_inner(name: String, default_title: Option<String>, default_goals: Option<Vec<String>>, notes: Option<String>) -> Result<WorkdayTemplate, String> {
    let n = now_iso();
    let t = WorkdayTemplate { id: new_id("tmpl"), name, default_title,
        default_goals: default_goals.unwrap_or_default(), notes,
        created_at: n.clone(), updated_at: n };
    persist_template(&t)?; Ok(t)
}
pub fn update_goal_inner(workday_id: String, goal_id: String, status: GoalStatus, text: Option<String>) -> Result<Workday, String> {
    let mut wd = load_wd(&workday_id)?;
    let g = wd.goals.iter_mut().find(|x| x.id == goal_id).ok_or_else(|| format!("goal {goal_id} not found"))?;
    g.status = status;
    if let Some(t) = text { g.text = t; }
    persist_workday(&wd)?; Ok(wd)
}
pub fn workday_list_inner(limit: Option<usize>) -> Result<Vec<Workday>, String> { list_workdays_inner(None, None, None, limit) }
