// Learn — guia de USO para exprimir el sistema al maximo.
// Objetivo: que sepas, ante cualquier tarea, cual es la herramienta MAS POTENTE
// y como combinarla. No es un tour de botones ni un catalogo de errores: es
// como sacarle el jugo a las skills, agentes, plugins, modos y memoria.
// Editable a mano. Sin emojis, sin rutas personales.

export type LearnSection = {
  topic: string;
  title: string;
  order: number;
  summary: string;
  markdown: string;
};

export const LEARN_SECTIONS: LearnSection[] = [
  {
    "topic": "elegir-herramienta",
    "title": "Elegir la herramienta mas potente",
    "order": 1,
    "summary": "El reflejo que mas potencia te da: ante cada tarea, decidir en 5 segundos si va sola, si necesita un experto, si necesita un proceso formal, o si toca el mundo exterior.",
    "markdown": "# Elegir la herramienta mas potente\n\nTu sistema no es una sola IA: es un orquestador con **expertos** (skills), **trabajadores aparte** (agentes), **procesos formales** (plugins) y **acciones al mundo** (MCPs). La mayor ganancia de potencia no es teclear mas, es **elegir bien la pieza** antes de empezar.\n\n## El checklist de 5 segundos\n\nAntes de pedir algo, responde cuatro preguntas:\n\n1. **Un dominio o varios?** Uno claro -> deja que el sistema lo resuelva. Varios o ambiguo -> sube a `/high` y nombra a los expertos.\n2. **Contexto aqui o trabajo aparte?** Necesito razonar contigo en este hilo -> **skill**. Es trabajo pesado que no quiero que llene el contexto (leer 40 ficheros, auditar el repo) -> **agente**.\n3. **Necesito un proceso?** (planificar, testear, debuggear, revisar) -> invoca el **plugin** explicito; no esperes que el routing lo adivine.\n4. **Toco el mundo exterior?** (repo, navegador, base de datos, busqueda web) -> es un **MCP**.\n\n## La diferencia que importa\n\n| Pieza | Que es | Cuesta | Cuando |\n|---|---|---|---|\n| **Skill** | Experto/proceso que se carga en TU conversacion | Tokens de tu contexto | Quieres a un especialista razonando contigo aqui |\n| **Agente** | Un Claude aparte, contexto propio, via `Task` | No ensucia tu contexto | Trabajo voluminoso o paralelo; te devuelve la conclusion |\n| **Plugin** | Paquete de skills/comandos con prefijo (`ecc:`, `superpowers:`, `codex:`) | Segun la skill | Necesitas un proceso probado (plan, TDD, review) |\n| **MCP** | Servidor que expone acciones (no contexto) | Por llamada | Mandar a GitHub, navegar, buscar, consultar codigo |\n\n## La regla de oro\n\n> Cuando importa de verdad, **no confies en el auto-routing: nombra tu la pieza.** El routing sugiere; tu decides. Teclear `hiper-plans`, `superpowers:writing-plans` o `Skill: rust-engineer` te garantiza la pieza potente. Para lo trivial, deja que el sistema enrute solo.\n\nLas secciones siguientes son el mapa de **cuales son las piezas mas potentes** y **cuando soltar cada una**."
  },
  {
    "topic": "planificar",
    "title": "Planificar a lo grande",
    "order": 2,
    "summary": "Antes de tocar codigo en algo no trivial, el plan es la mayor palanca. Cuando usar hiper-plans, los planificadores de ecc, superpowers:writing-plans y el Plan Mode nativo.",
    "markdown": "# Planificar a lo grande\n\nLa planificacion es donde mas se nota la diferencia entre pelear con el sistema y dominarlo. Un buen plan recorta el alcance, evita reescrituras y deja un artefacto que se puede ejecutar despues. Estas son las piezas potentes, de menor a mayor ceremonia:\n\n## Que invocar segun el caso\n\n| Situacion | Pieza | Por que |\n|---|---|---|\n| Trabajo dentro de este sistema, quiero un plan en disco | **`hiper-plans`** | Pensada para planificar aqui; deja el plan escrito para ejecutarlo luego |\n| Producto/feature nueva: definir el QUE antes del COMO | **`ecc:plan-prd`** | Genera un PRD; separa requisito de implementacion |\n| Feature sobre codigo existente, con sus convenciones | **`ecc:prp-plan`** | Produce un plan que alimenta `ecc:prp-implement` (estado nunca roto) |\n| El plan se va a ejecutar con subagentes/worktrees | **`superpowers:writing-plans`** | Pensado para ejecucion con la maquinaria de superpowers |\n| Decision grande que merece 2o/3er modelo | **`ecc:multi-plan`** | Trae mas de un modelo a deliberar |\n| Requisito vago, hay que explorar intencion primero | **`superpowers:brainstorming`** | Convierte una idea difusa en requisitos antes de planificar |\n\n## El Plan Mode nativo (Shift+Tab)\n\nEs **ortogonal** a las skills de arriba y se combina con ellas: bloquea la edicion hasta que apruebes el plan. Uselo cuando quieras revisar antes de que se toque una sola linea. `hiper-plans` + Plan Mode = plan estructurado en disco **y** freno de edicion hasta tu OK.\n\n## La mentalidad\n\n> Planificar bien es **cortar alcance**, no listar tareas. El entregable de un plan es la **linea de corte**: que entra en esta iteracion y que no. Si un plan no dice que NO vas a hacer, no es un plan.\n\nPara lo pequeno (un typo, un fix de una linea) no planifiques: hazlo. La ceremonia solo paga cuando el coste de equivocarse es alto."
  },
  {
    "topic": "ejecutar",
    "title": "Ejecutar con potencia",
    "order": 3,
    "summary": "Una vez hay plan, como ejecutarlo a maxima velocidad: motor de ejecucion de planes, agentes en paralelo, desarrollo dirigido por subagentes y workflows para trabajo masivo.",
    "markdown": "# Ejecutar con potencia\n\nTener un plan no basta; la potencia esta en **como lo ejecutas**. La diferencia entre hacerlo todo en un hilo y soltar varios trabajadores en paralelo es de horas.\n\n## Las piezas de ejecucion\n\n| Quiero... | Pieza | Que aporta |\n|---|---|---|\n| Ejecutar un plan ya escrito, con checkpoints | **`superpowers:executing-plans`** | Motor que sigue el plan paso a paso y para a revisar |\n| Lanzar varias tareas independientes a la vez | **`superpowers:dispatching-parallel-agents`** | Reparte trabajo sin estado compartido; tu sintetizas |\n| Implementar features con estado siempre coherente | **`ecc:prp-implement`** | Ejecuta el `prp-plan` sin dejar el repo a medias |\n| Desarrollo guiado por subagentes en esta sesion | **`superpowers:subagent-driven-development`** | Subagentes hacen el grueso, tu mantienes el hilo |\n| Trabajo full-stack grande | **`ecc:multi-workflow`** | Orquesta back + front + datos |\n| Quality gate dual antes de merge | **`ecc:santa-loop`** | Dos pasadas de calidad antes de tocar la rama principal |\n\n## Paralelo de verdad: agentes vs workflows\n\n- **Sesion interactiva, quieres checkpoints**: `dispatching-parallel-agents` o `subagent-driven-development`. Te paran a revisar entre fases.\n- **Trabajo masivo y mecanico** (migrar N ficheros, auditar todo el repo, evaluar por categorias): un **workflow**. Decenas de agentes en paralelo con sintesis final; corre en segundo plano y te avisa.\n\n## El reflejo que mas tiempo te ahorra\n\n> Si la tarea son **N cosas independientes**, no las hagas en serie. Suelta N agentes en un solo mensaje (o un workflow) y recoge el resultado. Lo secuencial solo se justifica cuando un paso depende del anterior."
  },
  {
    "topic": "expertos",
    "title": "Los expertos: skills y agentes",
    "order": 4,
    "summary": "El catalogo de especialistas: las personas de dominio, los agentes tecnicos por lenguaje/area, y la regla para decidir skill (aqui) vs agente (aparte).",
    "markdown": "# Los expertos: skills y agentes\n\nTu sistema tiene una flota de especialistas. La potencia esta en **traer al experto correcto** en vez de pedirle todo al generalista.\n\n## Dos familias\n\n- **Skills de dominio (personas)**: cargan contexto experto en TU hilo. Viven apagadas y se inyectan cuando las nombras. Hay personas de finanzas, negocio, diseno, gamedev, escritura, sistemas, etc. No son personajes: son **cargas de contexto especializado**.\n- **Agentes tecnicos**: subprocesos con contexto propio, lanzados con `Task`. Hay especialistas por lenguaje (Rust, TypeScript, Python, Go, C++, Swift, Kotlin...), por area (revision de codigo, seguridad, rendimiento, debugging, arquitectura, bases de datos, infra) y meta. Estan en `~/.claude/agents`.\n\n## Skill o agente?\n\n| Necesito... | Elige | Por que |\n|---|---|---|\n| Un experto razonando CONMIGO ahora | **Skill** | Comparte tu contexto, responde en linea |\n| Leer/auditar mucho sin llenar mi contexto | **Agente** | Trabaja aparte, te devuelve la conclusion |\n| Revisar el codigo que acabo de escribir | **Agente** `code-reviewer` o el del lenguaje | Mirada fresca, no contaminada |\n| Diagnosticar un bug o fallo de test | **Agente** `debugger` primero | Aisla el problema sin gastar tu hilo |\n| Decision de arquitectura | **Agente** `architect-reviewer` | Vision de sistema |\n| Cambio sensible (auth, secretos, pagos) | **Agente** `security-auditor` | Foco en amenazas |\n\n## Como invocar al experto correcto\n\n- **Nombralo**: decir su nombre es la senal mas fuerte; entra seguro. Para lo critico, no dejes que el routing lo adivine.\n- **Multi-perspectiva** (problemas dificiles): lanza varios a la vez con angulos distintos (arquitectura, seguridad, correccion, rendimiento, tests) y contrasta sus veredictos. Es el patron mas potente para decisiones de peso.\n- **Verifica que existe**: si invocas algo que no esta en disco, no opera. Ante la duda, nombra uno de los listados arriba."
  },
  {
    "topic": "segunda-opinion",
    "title": "Segunda opinion y anti-alucinacion",
    "order": 5,
    "summary": "Como traer un segundo o tercer modelo (Codex, Gemini) como pares para contrastar, refutar y evitar alucinaciones en decisiones que no te puedes permitir fallar.",
    "markdown": "# Segunda opinion y anti-alucinacion\n\nLa forma mas fiable de no equivocarte en algo importante es **no fiarte de una sola cabeza**. El sistema puede traer otros modelos como pares de solo lectura para contrastar.\n\n## Cuando traer un segundo modelo\n\n- **Decision con consecuencias** (arquitectura, una eleccion dificil de revertir): contrasta antes de comprometerte.\n- **Algo te huele raro** o suena demasiado seguro: pide refutacion explicita.\n- **Revision adversarial** de una implementacion: que otro modelo intente romperla.\n\n## Las piezas\n\n| Pieza | Que hace |\n|---|---|\n| **`/dual`** | Trae a Codex como par de solo lectura para una segunda opinion |\n| **`/triple`** | Codex + Gemini a la vez; tres angulos sobre el mismo problema |\n| **`codex:adversarial-review`** | Review que desafia el enfoque y las decisiones de diseno, no solo el codigo |\n| **`codex:review`** | Revision de codigo por un modelo distinto |\n| **`second-opinion`** | Skill para forzar una vision alternativa |\n| **`council`** | Varias voces estructuradas para decisiones ambiguas con tradeoffs |\n\n## El patron mas potente\n\n> Para una afirmacion que no te puedes permitir que sea falsa, **pide que la refuten, no que la confirmen**. Varios verificadores con el encargo de tumbar la idea cazan los errores que un solo \"si, correcto\" deja pasar. Si sobrevive a varios intentos de refutacion, puedes fiarte."
  },
  {
    "topic": "memoria",
    "title": "Memoria a lo grande",
    "order": 6,
    "summary": "Como aprovechar la memoria: recall hibrido, decisiones, contexto entre proyectos, y que se captura solo. La regla de oro de quien escribe.",
    "markdown": "# Memoria a lo grande\n\nLa memoria es lo que hace que el sistema no empiece de cero cada vez. Es propia, en Rust, con un **unico escritor** y recall semantico denso. No tienes que gestionarla a mano: trabaja sola y tu la aprovechas.\n\n## Que hace por ti, sin pedirlo\n\n- **Al abrir sesion**: te resume lo relevante (trabajos en curso, tareas, decisiones recientes).\n- **Al escribir un prompt**: precarga las memorias pertinentes y sugiere a quien delegar.\n- **Al cerrar / tras fallos**: propone guardar lo aprendido como candidatos a la bandeja de entrada (tu filtras).\n\n## Como exprimirla\n\n| Quiero... | Como |\n|---|---|\n| Recuperar algo que se de otra sesion | Pidelo por su concepto; el recall hibrido (texto + semantico) lo encuentra |\n| Que recuerde una decision importante | Pide guardarla; queda como decision recuperable |\n| Traer contexto de otro proyecto | El recall puede cruzar proyectos cuando hace falta |\n| Saber el estado del sistema de memoria | El sidecar tiene `stats`, `recall` y un chequeo de salud |\n\n## La regla de oro\n\n> Los hooks **proponen** candidatos; **nunca escriben memoria directamente**. Solo el servicio de memoria escribe la fuente de verdad. Eso evita que la memoria se contamine sola. Si quieres que algo perdure, pidelo explicito o acepta el candidato propuesto.\n\nLo importante para ti: **la memoria se captura sola, tu solo decides que merece quedarse.**"
  },
  {
    "topic": "ahorro-tokens",
    "title": "Ahorro de tokens",
    "order": 7,
    "summary": "Tres palancas para gastar menos sin perder calidad: filtrar salidas pesadas con RTK, skills perezosas que solo cargan lo necesario, y el modo mas bajo que cumpla.",
    "markdown": "# Ahorro de tokens\n\nMas potencia tambien es **durar mas con los mismos tokens**. Hay tres palancas, de mayor a menor impacto:\n\n## 1. Filtrar salidas pesadas (RTK)\n\nRTK (Rust Token Killer) recorta las salidas voluminosas (tests, builds, git, listados, JSON) **antes de que entren al contexto**, dejando solo lo accionable: fallos, diffs, lo que importa. Ahorros tipicos del 60-90% en operaciones comunes.\n\n- **Como se usa**: prefija el comando con `rtk` (por ejemplo `rtk cargo test`, `rtk git diff`). Si RTK tiene filtro para ese comando lo aplica; si no, pasa intacto, asi que siempre es seguro.\n- **Donde mas ahorra**: tests (90-99%), builds (70-87%), git (59-80%).\n\n## 2. Skills perezosas\n\nCasi todas las skills viven **apagadas a proposito**. Tener cientos activas reventaria el contexto cada sesion. El sistema solo enciende la que tu prompt justifica. Consecuencia practica: **nombrar la skill** es lo que la enciende; no esperes que esten todas cargadas.\n\n## 3. El modo mas bajo que cumpla\n\nNo uses un modo pesado para algo ligero. Un typo no necesita deliberacion. Reserva los modos altos para lo que de verdad lo merece (ver la seccion de modos).\n\n## La mentalidad\n\n> El token mas barato es el que no envias. Filtra el ruido (RTK), carga solo al experto que necesitas (lazy), y usa el modo justo. Las tres juntas multiplican cuanto trabajo cabe en una sesion."
  },
  {
    "topic": "codigo",
    "title": "Entender codigo al instante",
    "order": 8,
    "summary": "Como usar el grafo de codigo para que la IA no empiece a ciegas: quien llama a una funcion, que se rompe si la tocas, y donde vive cada simbolo.",
    "markdown": "# Entender codigo al instante\n\nCada vez que abres una sesion, la IA empieza **sin conocer tu codigo**. El grafo de codigo resuelve eso: es un indice de cada simbolo, llamada y fichero, que se consulta antes de escribir o editar.\n\n## Que preguntas responde\n\n| Pregunta | Para que sirve |\n|---|---|\n| Quien llama a esta funcion? | Saber el impacto antes de cambiarla |\n| Que se rompe si toco esto? | Analisis de impacto, evita regresiones |\n| Donde vive este simbolo? | Localizar sin grep a ciegas |\n| Como funciona esta area? | Mapa de un subsistema en una consulta |\n\n## Como sacarle el maximo\n\n- **Consultalo ANTES de editar**, no durante. Saber quien depende de una funcion cambia como la cambias.\n- Para \"como funciona X\" o \"como llega X a Y\", una sola consulta de exploracion suele devolver el codigo relevante agrupado por fichero. Es mas barato que un grep + lectura manual de decenas de ficheros.\n- El valor real no es *mirar* un grafo dibujado, es que **la respuesta llegue con el contexto del codigo ya dentro**.\n\n## La mentalidad\n\n> Antes de tocar una funcion compartida, pregunta primero quien la usa. Cinco segundos de consulta evitan una regresion silenciosa."
  },
  {
    "topic": "modos",
    "title": "Los modos y como hablarle",
    "order": 9,
    "summary": "Los modos de intensidad (low, high, ultra, thinking) y como se invocan. La regla: el modo mas bajo que cumpla, y subir solo cuando la tarea lo pide.",
    "markdown": "# Los modos y como hablarle\n\nPuedes ajustar **cuanta deliberacion** pones en cada peticion. Los modos se reconocen como patrones en tu frase; los tecleas dentro del prompt normal.\n\n## Los niveles\n\n| Modo | Cuando |\n|---|---|\n| `/low` | Respuesta corta, sin delegacion, una sola accion. Typos, datos sueltos |\n| (por defecto) | Trabajo normal; enruta sin deliberar de mas |\n| `/high` | Feature dura, bug misterioso, multi-dominio. Sube y nombra a los expertos |\n| `/ultra` | Decision arquitectonica critica; maxima deliberacion |\n| `/thinking` | Apila varios enfoques con sus tradeoffs antes de actuar |\n| `/dual`, `/triple` | Trae a Codex / Gemini como pares (ver Segunda opinion) |\n\n## La regla de oro\n\n> Usa **el modo mas bajo que cumpla**. No pidas `/ultra` para un typo ni `/low` para una decision de arquitectura. La potencia no es ir siempre al maximo: es ajustar el esfuerzo a lo que la tarea pide.\n\n## El reflejo completo\n\n1. **Un dominio trivial** -> por defecto, o `/low`.\n2. **Varios dominios o algo dificil** -> `/high` y nombra a los expertos.\n3. **Decision que no puedes revertir facil** -> `/ultra` y trae un segundo modelo (`/dual`).\n4. **No sabes por donde empezar** -> deja que el orquestador proponga, luego afina."
  },
  {
    "topic": "recetas",
    "title": "Recetas: flujos completos",
    "order": 10,
    "summary": "Cuatro flujos de principio a fin que combinan las piezas anteriores: feature nueva, bug dificil, decision de peso e investigacion. El como se encadena todo.",
    "markdown": "# Recetas: flujos completos\n\nLas piezas sueltas valen poco; la potencia esta en **encadenarlas**. Cuatro flujos de referencia:\n\n## Feature nueva (no trivial)\n\n1. **Plan**: `ecc:plan-prd` (el QUE) o `hiper-plans` (trabajo en este sistema). Recorta el alcance.\n2. **Plan de implementacion**: `ecc:prp-plan` sobre el codigo existente.\n3. **Ejecucion**: `ecc:prp-implement` o `superpowers:executing-plans` con checkpoints.\n4. **Revision**: agente `code-reviewer` + el especialista del lenguaje.\n5. **Calidad antes de cerrar**: `ecc:santa-loop` o una pasada de seguridad si toca datos sensibles.\n\n## Bug dificil\n\n1. **Diagnostico**: agente `debugger` PRIMERO (aisla la causa sin gastar tu hilo).\n2. **Si cruza servicios**: agente `error-detective` para correlacionar.\n3. **Proceso disciplinado**: `superpowers:systematic-debugging` para no saltar a conclusiones.\n4. **Fix + verificacion**: arregla y confirma que falla cuando debe fallar (caso negativo).\n\n## Decision de peso\n\n1. **Explora la intencion**: `superpowers:brainstorming` si el requisito es difuso.\n2. **Plan con varios modelos**: `ecc:multi-plan`.\n3. **Contraste**: `/dual` o `/triple` para refutar antes de comprometerte.\n4. **Decide y guarda la decision** en memoria para no re-litigarla.\n\n## Investigacion / research\n\n1. **Busca primero lo que ya existe** (codigo, docs de la libreria, registros de paquetes) antes de escribir nada nuevo.\n2. **Multi-fuente con verificacion**: un flujo de research que abre varias busquedas, lee fuentes y verifica las afirmaciones de forma adversarial.\n3. **Sintetiza** con fuentes citadas; no te quedes con la primera respuesta.\n\n## La idea de fondo\n\n> Planificar -> ejecutar -> revisar -> recordar. Cada eslabon tiene su pieza mas potente. Encadenarlos bien es la diferencia entre usar el sistema y dominarlo."
  }
];
