// ULTRON Control Center — Skills module.
//
// Single source of truth: ~/.ultron/skills/registry.json. That file is
// regenerated by `skill_vault.py registry` on every Stop hook, so it stays
// in sync with the real filesystem state. Frontend just reads it.
//
// Schema (v2):
//   { "schema_version": 2, "generated_at": "...", "counts": {...},
//     "skills": [{name, state, source, path, description, tags,
//                 usage_count, embedding_id, ...}] }
//
// State values: "active" | "plugin" | "vaulted"
//   active   → ~/.claude/skills/<name>/SKILL.md
//   plugin   → installed as Claude Code plugin
//   vaulted  → ~/.ultron/skill-vault/<name>/SKILL.md

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Clone)]
pub struct SkillInfo {
    pub name: String,
    pub state: String,
    pub source: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub path: Option<String>,
    pub usage_count: u64,
}

// registry.json shape (v2): "skills" is a *map* keyed by composite ids like
// "active::academic-deep-research" / "plugin::commit" / "vaulted::xyz". The
// values carry the canonical "name" and "state" fields so we discard the
// map key when flattening to a Vec.
#[derive(Debug, Deserialize)]
struct RegistryRoot {
    #[serde(default)]
    skills: BTreeMap<String, RegistrySkill>,
}

#[derive(Debug, Deserialize)]
struct RegistrySkill {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    state: Option<String>,
    #[serde(default)]
    source: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    tags: Vec<String>,
    #[serde(default)]
    path: Option<String>,
    #[serde(default)]
    usage_count: u64,
}

fn registry_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".ultron/skills/registry.json"))
}

/// Strip non-Latin characters (CJK, Cyrillic, Hebrew, Arabic, …) from a
/// string while preserving ASCII + Latin Extended (so Spanish accents
/// like á é í ó ú ñ are kept). Collapses leftover whitespace and orphan
/// punctuation introduced by the strip.
fn strip_non_latin(s: &str) -> String {
    let replaced: String = s
        .chars()
        .map(|c| {
            let cp = c as u32;
            // ASCII (0x00–0x7F), Latin-1 Supplement + Latin Extended-A + B
            // (0xC0–0x24F), plus a few Latin Extended Additional (0x1E00–0x1EFF).
            if cp < 0x80 || (0xC0..=0x24F).contains(&cp) || (0x1E00..=0x1EFF).contains(&cp) {
                c
            } else {
                ' '
            }
        })
        .collect();

    // Collapse double spaces and orphan punctuation that the strip leaves
    // behind (e.g. "research, 研究, deep" → "research, , deep" → "research, deep").
    let mut out = replaced;
    while out.contains("  ") {
        out = out.replace("  ", " ");
    }
    for pat in &[",  ,", ", ,", " ,", ", ", ",,"] {
        while out.contains(pat) {
            out = out.replace(",,", ",");
            out = out.replace(", ,", ",");
            out = out.replace(" ,", ",");
        }
    }
    // Re-space after commas for readability
    out = out.replace(",", ", ");
    while out.contains("  ") {
        out = out.replace("  ", " ");
    }
    out.trim_matches(|c: char| c == ',' || c.is_whitespace())
        .to_string()
}

pub fn list_skills_inner() -> Result<Vec<SkillInfo>, String> {
    let path = registry_path().ok_or_else(|| "no HOME".to_string())?;
    let raw = fs::read_to_string(&path)
        .map_err(|e| format!("read registry.json: {} ({})", e, path.display()))?;
    let root: RegistryRoot =
        serde_json::from_str(&raw).map_err(|e| format!("parse registry.json: {}", e))?;

    let mut out: Vec<SkillInfo> = Vec::with_capacity(root.skills.len());
    for (key, s) in root.skills.into_iter() {
        // Prefer the explicit "name" field; fall back to the suffix of the
        // composite key ("active::foo" → "foo") when missing.
        let name = match s.name {
            Some(n) => n,
            None => key.split("::").nth(1).unwrap_or(&key).to_string(),
        };
        let cleaned_desc = s.description.map(|d| strip_non_latin(&d));
        let cleaned_tags: Vec<String> = s
            .tags
            .into_iter()
            .map(|t| strip_non_latin(&t))
            .filter(|t| !t.is_empty())
            .collect();
        out.push(SkillInfo {
            name,
            state: s.state.unwrap_or_else(|| "unknown".to_string()),
            source: s.source,
            description: cleaned_desc.filter(|d| !d.is_empty()),
            tags: cleaned_tags,
            path: s.path,
            usage_count: s.usage_count,
        });
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// SKILL.md preview
// ---------------------------------------------------------------------------

/// Try to read the SKILL.md for a skill by name. Resolution order:
///   1. registry-recorded path (if present and points to a dir)
///   2. ~/.claude/skills/<name>/SKILL.md  (active layer)
///   3. ~/.ultron/skill-vault/<name>/SKILL.md  (vault layer)
/// Same Latin-only sanitization for SKILL.md preview content.
pub fn read_skill_md_inner_raw(name: &str) -> Result<String, String> {
    read_skill_md_internal(name)
}

pub fn read_skill_md_inner(name: &str) -> Result<String, String> {
    read_skill_md_internal(name).map(|c| strip_non_latin(&c))
}

fn read_skill_md_internal(name: &str) -> Result<String, String> {
    // 1. registry path
    let Some(home) = dirs::home_dir() else {
        return Err("no HOME".to_string());
    };
    let all = list_skills_inner()?;
    if let Some(s) = all.iter().find(|s| s.name == name) {
        if let Some(p) = &s.path {
            let candidate = Path::new(p).join("SKILL.md");
            if let Ok(contents) = fs::read_to_string(&candidate) {
                return Ok(contents);
            }
        }
    }

    let candidates: &[PathBuf] = &[
        home.join(format!(".claude/skills/{}/SKILL.md", name)),
        home.join(format!(".ultron/skill-vault/{}/SKILL.md", name)),
    ];
    for c in candidates {
        if let Ok(contents) = fs::read_to_string(c) {
            return Ok(contents);
        }
    }
    Err(format!("SKILL.md not found for '{}'", name))
}
