// ULTRON Control Center — Skills module.
//
// Single source of truth: ~/.ultron/skills/registry.json. That file is
// regenerated by `skill_vault.py registry` on every Stop hook, so it stays
// in sync with the real filesystem state. Frontend just reads it.
//
// Schema (v2):
//   { "schema_version": 2, "generated_at": "...", "counts": {...},
//     "skills": [{name, state, source, path, description, tags,
//                 usage_count, embedding_id, ...}] }
//
// State values: "active" | "plugin" | "vaulted"
//   active   → ~/.claude/skills/<name>/SKILL.md
//   plugin   → installed as Claude Code plugin
//   vaulted  → ~/.ultron/skill-vault/<name>/SKILL.md

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Clone)]
pub struct SkillInfo {
    pub name: String,
    pub state: String,
    pub source: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub path: Option<String>,
    pub usage_count: u64,
}

#[derive(Debug, Deserialize)]
struct RegistryRoot {
    #[serde(default)]
    skills: Vec<RegistrySkill>,
}

#[derive(Debug, Deserialize)]
struct RegistrySkill {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    state: Option<String>,
    #[serde(default)]
    source: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    tags: Vec<String>,
    #[serde(default)]
    path: Option<String>,
    #[serde(default)]
    usage_count: u64,
}

fn registry_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".ultron/skills/registry.json"))
}

pub fn list_skills_inner() -> Result<Vec<SkillInfo>, String> {
    let path = registry_path().ok_or_else(|| "no HOME".to_string())?;
    let raw = fs::read_to_string(&path)
        .map_err(|e| format!("read registry.json: {} ({})", e, path.display()))?;
    let root: RegistryRoot =
        serde_json::from_str(&raw).map_err(|e| format!("parse registry.json: {}", e))?;

    let mut out: Vec<SkillInfo> = Vec::with_capacity(root.skills.len());
    for s in root.skills.into_iter() {
        let Some(name) = s.name else { continue };
        out.push(SkillInfo {
            name,
            state: s.state.unwrap_or_else(|| "unknown".to_string()),
            source: s.source,
            description: s.description,
            tags: s.tags,
            path: s.path,
            usage_count: s.usage_count,
        });
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// SKILL.md preview
// ---------------------------------------------------------------------------

/// Try to read the SKILL.md for a skill by name. Resolution order:
///   1. registry-recorded path (if present and points to a dir)
///   2. ~/.claude/skills/<name>/SKILL.md  (active layer)
///   3. ~/.ultron/skill-vault/<name>/SKILL.md  (vault layer)
pub fn read_skill_md_inner(name: &str) -> Result<String, String> {
    // 1. registry path
    let Some(home) = dirs::home_dir() else {
        return Err("no HOME".to_string());
    };
    let all = list_skills_inner()?;
    if let Some(s) = all.iter().find(|s| s.name == name) {
        if let Some(p) = &s.path {
            let candidate = Path::new(p).join("SKILL.md");
            if let Ok(contents) = fs::read_to_string(&candidate) {
                return Ok(contents);
            }
        }
    }

    let candidates: &[PathBuf] = &[
        home.join(format!(".claude/skills/{}/SKILL.md", name)),
        home.join(format!(".ultron/skill-vault/{}/SKILL.md", name)),
    ];
    for c in candidates {
        if let Ok(contents) = fs::read_to_string(c) {
            return Ok(contents);
        }
    }
    Err(format!("SKILL.md not found for '{}'", name))
}
