// ULTRON Control Center — Skills module.
//
// Single source of truth: ~/.ultron/skills/registry.json. That file is
// regenerated by `skill_vault.py registry` on every Stop hook, so it stays
// in sync with the real filesystem state. Frontend just reads it.
//
// Schema (v2):
//   { "schema_version": 2, "generated_at": "...", "counts": {...},
//     "skills": [{name, state, source, path, description, tags,
//                 usage_count, embedding_id, ...}] }
//
// State values: "active" | "plugin" | "vaulted"
//   active   → ~/.claude/skills/<name>/SKILL.md
//   plugin   → installed as Claude Code plugin
//   vaulted  → ~/.ultron/skill-vault/<name>/SKILL.md

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Clone)]
pub struct SkillInfo {
    pub name: String,
    pub state: String,
    pub source: Option<String>,
    pub description: Option<String>,
    pub tags: Vec<String>,
    pub path: Option<String>,
    pub usage_count: u64,
    /// Routing priority for conflict resolution when multiple skills match the
    /// same trigger. Range 1–10; higher value wins. Skills without an explicit
    /// `priority:` frontmatter field default to 5.
    pub priority: u8,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub security: Option<SecurityInfo>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SecurityInfo {
    pub decision: String,
    #[serde(default)]
    pub findings_count: u64,
    #[serde(default)]
    pub high_severity_rules: Vec<String>,
    #[serde(default)]
    pub sha1: Option<String>,
    #[serde(default)]
    pub scanned_at: Option<String>,
}

// registry.json shape (v2): "skills" is a *map* keyed by composite ids like
// "active::academic-deep-research" / "plugin::commit" / "vaulted::xyz". The
// values carry the canonical "name" and "state" fields so we discard the
// map key when flattening to a Vec.
#[derive(Debug, Deserialize)]
struct RegistryRoot {
    #[serde(default)]
    skills: BTreeMap<String, RegistrySkill>,
}

#[derive(Debug, Deserialize)]
struct RegistrySkill {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    state: Option<String>,
    #[serde(default)]
    source: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    tags: Vec<String>,
    #[serde(default)]
    path: Option<String>,
    #[serde(default)]
    usage_count: u64,
    /// Optional priority field written by skill_vault.py registry or parsed
    /// directly from SKILL.md frontmatter. `None` serialises as absent JSON
    /// key; the consumer treats it as 5 (mid-range default).
    #[serde(default)]
    priority: Option<u8>,
    #[serde(default)]
    security: Option<SecurityInfo>,
}

fn registry_path() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".ultron/skills/registry.json"))
}

/// Strip non-Latin characters (CJK, Cyrillic, Hebrew, Arabic, …) from a
/// string while preserving ASCII + Latin Extended (so Spanish accents
/// like á é í ó ú ñ are kept). Collapses leftover whitespace and orphan
/// punctuation introduced by the strip.
fn strip_non_latin(s: &str) -> String {
    let replaced: String = s
        .chars()
        .map(|c| {
            let cp = c as u32;
            // ASCII (0x00–0x7F), Latin-1 Supplement + Latin Extended-A + B
            // (0xC0–0x24F), plus a few Latin Extended Additional (0x1E00–0x1EFF).
            if cp < 0x80 || (0xC0..=0x24F).contains(&cp) || (0x1E00..=0x1EFF).contains(&cp) {
                c
            } else {
                ' '
            }
        })
        .collect();

    // Collapse double spaces and orphan punctuation that the strip leaves
    // behind (e.g. "research, 研究, deep" → "research,  , deep" → "research, deep").
    let mut out = replaced;
    // Iterative cleanup with a hard cap so a pathological input can never spin.
    for _ in 0..6 {
        let before = out.len();
        out = out.replace("  ", " ");
        out = out.replace(" ,", ",");
        out = out.replace(",,", ",");
        if out.len() == before {
            break;
        }
    }
    // Restore a single space after each comma for readability.
    out = out.replace(",", ", ");
    // Final whitespace collapse (bounded — no while).
    while out.contains("  ") {
        out = out.replace("  ", " ");
    }
    out.trim_matches(|c: char| c == ',' || c.is_whitespace())
        .to_string()
}

pub fn list_skills_inner() -> Result<Vec<SkillInfo>, String> {
    let path = registry_path().ok_or_else(|| "no HOME".to_string())?;
    let raw = fs::read_to_string(&path)
        .map_err(|e| format!("read registry.json: {} ({})", e, path.display()))?;
    let root: RegistryRoot =
        serde_json::from_str(&raw).map_err(|e| format!("parse registry.json: {}", e))?;

    let mut out: Vec<SkillInfo> = Vec::with_capacity(root.skills.len());
    for (key, s) in root.skills.into_iter() {
        // Prefer the explicit "name" field; fall back to the suffix of the
        // composite key ("active::foo" → "foo") when missing.
        let name = match s.name {
            Some(n) => n,
            None => key.split("::").nth(1).unwrap_or(&key).to_string(),
        };
        let cleaned_desc = s.description.map(|d| strip_non_latin(&d));
        let cleaned_tags: Vec<String> = s
            .tags
            .into_iter()
            .map(|t| strip_non_latin(&t))
            .filter(|t| !t.is_empty())
            .collect();
        // Clamp to 1..=10; absent → 5 (mid-range default).
        let priority = s.priority.map(|p| p.clamp(1, 10)).unwrap_or(5);
        out.push(SkillInfo {
            name,
            state: s.state.unwrap_or_else(|| "unknown".to_string()),
            source: s.source,
            description: cleaned_desc.filter(|d| !d.is_empty()),
            tags: cleaned_tags,
            path: s.path,
            usage_count: s.usage_count,
            priority,
            security: s.security,
        });
    }
    // Sort by priority descending so the frontend and any caller that needs
    // deterministic conflict resolution between same-trigger skills always
    // receives the highest-priority skill first.
    out.sort_by(|a, b| b.priority.cmp(&a.priority).then(a.name.cmp(&b.name)));
    Ok(out)
}

// ---------------------------------------------------------------------------
// SKILL.md preview
// ---------------------------------------------------------------------------

/// Try to read the SKILL.md for a skill by name. Resolution order:
///   1. registry-recorded path (if present and points to a dir)
///   2. ~/.claude/skills/<name>/SKILL.md  (active layer)
///   3. ~/.ultron/skill-vault/<name>/SKILL.md  (vault layer)
/// Same Latin-only sanitization for SKILL.md preview content.
//
// v15.3.6 cleanup: read_skill_md_inner_raw() removed (no callers — every
// public entry sanitises Latin chars via read_skill_md_inner). Restore
// from git history if a raw bytestring variant is ever needed.

pub fn read_skill_md_inner(name: &str) -> Result<String, String> {
    read_skill_md_internal(name).map(|c| strip_non_latin(&c))
}

fn read_skill_md_internal(name: &str) -> Result<String, String> {
    // SECURITY (v15.3.6 CC-04): without this validation, a renderer can
    // pass `name = "../../../Windows/System32/drivers/etc/hosts/.."` and
    // walk the FS for any file named SKILL.md. validate_slug() rejects
    // anything outside [a-z0-9-]{2,61} starting with [a-z0-9], which is
    // the same shape skills already enforce on create/update/delete.
    validate_slug(name)?;
    // 1. registry path
    let Some(home) = dirs::home_dir() else {
        return Err("no HOME".to_string());
    };
    let all = list_skills_inner()?;
    if let Some(s) = all.iter().find(|s| s.name == name) {
        if let Some(p) = &s.path {
            let candidate = Path::new(p).join("SKILL.md");
            if let Ok(contents) = fs::read_to_string(&candidate) {
                return Ok(contents);
            }
        }
    }

    let candidates: &[PathBuf] = &[
        home.join(format!(".claude/skills/{}/SKILL.md", name)),
        home.join(format!(".ultron/skill-vault/{}/SKILL.md", name)),
    ];
    for c in candidates {
        if let Ok(contents) = fs::read_to_string(c) {
            return Ok(contents);
        }
    }
    Err(format!("SKILL.md not found for '{}'", name))
}

// ---------------------------------------------------------------------------
// CRUD — create / update / delete
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize)]
pub struct SkillCreateResult {
    pub success: bool,
    pub name: String,
    pub path: String,
    pub layer: String,
}

#[derive(Debug, Serialize)]
pub struct SkillUpdateResult {
    pub success: bool,
    pub name: String,
    pub path: String,
    pub backup_path: String,
}

#[derive(Debug, Serialize)]
pub struct SkillDeleteResult {
    pub success: bool,
    pub name: String,
    pub from_path: String,
    pub to_path: String,
    pub soft: bool,
}

/// Validate slug per the spec: `^[a-z0-9][a-z0-9-]{1,60}$`.
fn validate_slug(name: &str) -> Result<(), String> {
    let len = name.len();
    if !(2..=61).contains(&len) {
        return Err(format!("invalid slug length ({}): 2..=61 expected", len));
    }
    let bytes = name.as_bytes();
    let first_ok = bytes[0].is_ascii_lowercase() || bytes[0].is_ascii_digit();
    if !first_ok {
        return Err("slug must start with [a-z0-9]".to_string());
    }
    for &b in &bytes[1..] {
        let ok = b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-';
        if !ok {
            return Err("slug allowed chars: [a-z0-9-]".to_string());
        }
    }
    Ok(())
}

fn unix_ts() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn layer_root(home: &Path, layer: &str) -> Result<PathBuf, String> {
    match layer {
        "active" => Ok(home.join(".claude/skills")),
        "vaulted" => Ok(home.join(".ultron/skill-vault")),
        other => Err(format!(
            "invalid layer '{}': expected active|vaulted",
            other
        )),
    }
}

/// Locate an existing skill dir. Looks in active first, then vault.
fn locate_skill_dir(home: &Path, name: &str) -> Result<PathBuf, String> {
    let active = home.join(format!(".claude/skills/{}", name));
    if active.is_dir() {
        return Ok(active);
    }
    let vault = home.join(format!(".ultron/skill-vault/{}", name));
    if vault.is_dir() {
        return Ok(vault);
    }
    Err(format!("skill dir not found for '{}'", name))
}

/// Create a new skill. Validates slug, ensures the target dir does not yet
/// exist, writes SKILL.md with YAML frontmatter + body.
pub fn create_skill_inner(
    name: String,
    description: String,
    body: String,
    layer: String,
) -> Result<SkillCreateResult, String> {
    validate_slug(&name)?;
    let desc_trim = description.trim();
    if desc_trim.is_empty() || desc_trim.len() > 300 {
        return Err("description must be 1..=300 chars".to_string());
    }
    let home = dirs::home_dir().ok_or_else(|| "no HOME".to_string())?;
    let root = layer_root(&home, &layer)?;
    let dir = root.join(&name);
    if dir.exists() {
        return Err(format!("skill dir already exists: {}", dir.display()));
    }
    fs::create_dir_all(&dir).map_err(|e| format!("mkdir {}: {}", dir.display(), e))?;

    let body_trim = body.trim_end();
    let contents = format!(
        "---\nname: {}\ndescription: {}\n---\n\n{}\n",
        name,
        desc_trim.replace('\n', " "),
        body_trim
    );
    let md_path = dir.join("SKILL.md");
    fs::write(&md_path, contents).map_err(|e| format!("write SKILL.md: {}", e))?;

    Ok(SkillCreateResult {
        success: true,
        name,
        path: md_path.to_string_lossy().to_string(),
        layer,
    })
}

/// Overwrite an existing SKILL.md after backing up the previous version to
/// ~/.ultron/backups/skill-edits/<name>-<ts>.md. Refuses if the file is missing.
pub fn update_skill_md_inner(name: String, content: String) -> Result<SkillUpdateResult, String> {
    validate_slug(&name)?;
    let home = dirs::home_dir().ok_or_else(|| "no HOME".to_string())?;
    let dir = locate_skill_dir(&home, &name)?;
    let md_path = dir.join("SKILL.md");
    if !md_path.is_file() {
        return Err(format!("SKILL.md not found at {}", md_path.display()));
    }

    let backup_dir = home.join(".ultron/backups/skill-edits");
    fs::create_dir_all(&backup_dir)
        .map_err(|e| format!("mkdir {}: {}", backup_dir.display(), e))?;
    let backup_path = backup_dir.join(format!("{}-{}.md", name, unix_ts()));
    fs::copy(&md_path, &backup_path)
        .map_err(|e| format!("backup copy {}: {}", backup_path.display(), e))?;

    fs::write(&md_path, content).map_err(|e| format!("write SKILL.md: {}", e))?;

    Ok(SkillUpdateResult {
        success: true,
        name,
        path: md_path.to_string_lossy().to_string(),
        backup_path: backup_path.to_string_lossy().to_string(),
    })
}

/// Move a skill dir.
///   soft=true  → demote to ~/.ultron/skill-vault/<name>
///   soft=false → archive to ~/.ultron/backups/skill-deleted/<name>-<ts>
/// Never recursively deletes.
pub fn delete_skill_inner(name: String, soft: bool) -> Result<SkillDeleteResult, String> {
    validate_slug(&name)?;
    let home = dirs::home_dir().ok_or_else(|| "no HOME".to_string())?;
    let from = locate_skill_dir(&home, &name)?;

    let to = if soft {
        let dest_root = home.join(".ultron/skill-vault");
        fs::create_dir_all(&dest_root)
            .map_err(|e| format!("mkdir {}: {}", dest_root.display(), e))?;
        let dest = dest_root.join(&name);
        if dest.exists() {
            return Err(format!(
                "vault destination already exists: {}",
                dest.display()
            ));
        }
        // Already in vault? No-op-soft would be a contradiction; refuse.
        if from == dest {
            return Err("skill is already in vault layer".to_string());
        }
        dest
    } else {
        let dest_root = home.join(".ultron/backups/skill-deleted");
        fs::create_dir_all(&dest_root)
            .map_err(|e| format!("mkdir {}: {}", dest_root.display(), e))?;
        dest_root.join(format!("{}-{}", name, unix_ts()))
    };

    // Try fast rename first; fall back to copy+remove for cross-volume moves.
    if let Err(_e) = fs::rename(&from, &to) {
        copy_dir_recursive(&from, &to)
            .map_err(|e| format!("copy fallback {}→{}: {}", from.display(), to.display(), e))?;
        fs::remove_dir_all(&from).map_err(|e| format!("remove src {}: {}", from.display(), e))?;
    }

    Ok(SkillDeleteResult {
        success: true,
        name,
        from_path: from.to_string_lossy().to_string(),
        to_path: to.to_string_lossy().to_string(),
        soft,
    })
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ft = entry.file_type()?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if ft.is_dir() {
            copy_dir_recursive(&from, &to)?;
        } else {
            fs::copy(&from, &to)?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Hashing + date helpers (reused by agents.rs for waiver YAML)
// ---------------------------------------------------------------------------

/// Convert a unix timestamp (UTC seconds) into a `YYYY-MM-DD` string.
/// Howard Hinnant's civil-from-days algorithm — pure stdlib, no deps.
/// Made `pub(crate)` so the agents module can reuse it for waiver YAML.
#[allow(dead_code)]
pub(crate) fn format_ymd_local(ts: u64) -> String {
    let days = (ts / 86400) as i64;
    let z = days + 719468;
    let era = if z >= 0 {
        z / 146097
    } else {
        (z - 146096) / 146097
    };
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let mut y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    if m <= 2 {
        y += 1;
    }
    format!("{:04}-{:02}-{:02}", y, m, d)
}

/// SHA1 hash of an on-disk file as a 40-char hex string. `pub(crate)` so
/// the agents module reuses the same hashing engine without dragging in
/// a new crate dep.
#[allow(dead_code)]
pub(crate) fn sha1_of_file(p: &Path) -> Result<String, String> {
    let data = fs::read(p).map_err(|e| format!("read {}: {}", p.display(), e))?;
    let mut hasher = Sha1Engine::new();
    hasher.update(&data);
    Ok(hasher.hex())
}

// Minimal in-tree SHA1 to avoid a new crate dep just for this command.
// `pub(crate)` so the agents module reuses the same engine.
pub(crate) struct Sha1Engine {
    state: [u32; 5],
    buf: Vec<u8>,
    len: u64,
}

impl Sha1Engine {
    pub(crate) fn new() -> Self {
        Self {
            state: [0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0],
            buf: Vec::new(),
            len: 0,
        }
    }
    pub(crate) fn update(&mut self, data: &[u8]) {
        self.len += data.len() as u64;
        self.buf.extend_from_slice(data);
        let mut idx = 0;
        while self.buf.len() - idx >= 64 {
            self.process_block(&self.buf[idx..idx + 64].try_into().unwrap());
            idx += 64;
        }
        self.buf.drain(..idx);
    }
    pub(crate) fn hex(mut self) -> String {
        let bit_len = self.len * 8;
        self.buf.push(0x80);
        while self.buf.len() % 64 != 56 {
            self.buf.push(0);
        }
        self.buf.extend_from_slice(&bit_len.to_be_bytes());
        let mut idx = 0;
        while idx < self.buf.len() {
            let block: [u8; 64] = self.buf[idx..idx + 64].try_into().unwrap();
            self.process_block(&block);
            idx += 64;
        }
        let mut out = String::with_capacity(40);
        for word in self.state {
            out.push_str(&format!("{:08x}", word));
        }
        out
    }
    fn process_block(&mut self, block: &[u8; 64]) {
        let mut w = [0u32; 80];
        for i in 0..16 {
            w[i] = u32::from_be_bytes(block[i * 4..i * 4 + 4].try_into().unwrap());
        }
        for i in 16..80 {
            let val = w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16];
            w[i] = val.rotate_left(1);
        }
        let mut a = self.state[0];
        let mut b = self.state[1];
        let mut c = self.state[2];
        let mut d = self.state[3];
        let mut e = self.state[4];
        for i in 0..80 {
            let (f, k) = match i {
                0..=19 => ((b & c) | (!b & d), 0x5A827999),
                20..=39 => (b ^ c ^ d, 0x6ED9EBA1),
                40..=59 => ((b & c) | (b & d) | (c & d), 0x8F1BBCDC),
                _ => (b ^ c ^ d, 0xCA62C1D6),
            };
            let temp = a
                .rotate_left(5)
                .wrapping_add(f)
                .wrapping_add(e)
                .wrapping_add(k)
                .wrapping_add(w[i]);
            e = d;
            d = c;
            c = b.rotate_left(30);
            b = a;
            a = temp;
        }
        self.state[0] = self.state[0].wrapping_add(a);
        self.state[1] = self.state[1].wrapping_add(b);
        self.state[2] = self.state[2].wrapping_add(c);
        self.state[3] = self.state[3].wrapping_add(d);
        self.state[4] = self.state[4].wrapping_add(e);
    }
}

// ---------------------------------------------------------------------------
// Origin-aware listing (Control Center 2.0 / P2)
//
// New `SkillEntry` type that surfaces the *origin* of every skill (global /
// project / plugin) so the Skills.tsx viewer can paint scope chips and let
// the user toggle global skills on/off via a rename to `_disabled/`. Lives
// next to the registry-driven `SkillInfo` (still used by the older preview
// + CRUD path) — both coexist until the frontend is fully migrated.
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub enum SkillOrigin {
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "plugin")]
    Plugin,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SkillEntry {
    pub name: String,
    pub path: String,
    pub description: String,
    pub origin: SkillOrigin,
    pub enabled: bool,
}

fn global_skills_dir() -> Result<PathBuf, String> {
    let home = dirs::home_dir().ok_or("no home dir")?;
    Ok(home.join(".claude").join("skills"))
}

fn project_skills_dir(project_path: &str) -> PathBuf {
    PathBuf::from(project_path).join(".claude").join("skills")
}

/// Plugin skills live three levels deep:
/// `~/.claude/plugins/cache/<plugin-id>/<plugin-name>/<version>/skills/`.
/// For each `<plugin-id>/<plugin-name>` pair we keep only the latest
/// version dir (sorted lexicographically descending — works for stable
/// semver tags; `-rc`/`-alpha` suffixes fall back to a sane lex order).
fn plugin_skills_dirs() -> Vec<PathBuf> {
    let Some(home) = dirs::home_dir() else {
        return Vec::new();
    };
    let cache = home.join(".claude").join("plugins").join("cache");
    let mut out = Vec::new();
    let Ok(plugin_ids) = std::fs::read_dir(&cache) else {
        return out;
    };
    for pid_entry in plugin_ids.flatten() {
        let pid_path = pid_entry.path();
        if !pid_path.is_dir() {
            continue;
        }
        let Ok(plugin_names) = std::fs::read_dir(&pid_path) else {
            continue;
        };
        for pname_entry in plugin_names.flatten() {
            let pname_path = pname_entry.path();
            if !pname_path.is_dir() {
                continue;
            }
            // Collect version dirs, keep the lex-desc latest.
            let mut versions: Vec<PathBuf> = match std::fs::read_dir(&pname_path) {
                Ok(rd) => rd
                    .flatten()
                    .map(|e| e.path())
                    .filter(|p| p.is_dir())
                    .collect(),
                Err(_) => continue,
            };
            versions.sort_by(|a, b| {
                let an = a.file_name().and_then(|s| s.to_str()).unwrap_or("");
                let bn = b.file_name().and_then(|s| s.to_str()).unwrap_or("");
                bn.cmp(an)
            });
            if let Some(latest) = versions.first() {
                let skills = latest.join("skills");
                if skills.is_dir() {
                    out.push(skills);
                }
            }
        }
    }
    out
}

/// Parse `(name, description, enabled, is_valid_skill)` from a skill dir.
///
/// A real skill is a DIRECTORY containing `SKILL.md` whose YAML frontmatter
/// declares at least `name:` and `description:`. Anything else is rejected
/// as a false positive.
///
/// **Disabled detection** — two conventions are supported in parallel:
///   1. Suffix `.disabled` on the folder itself (e.g. `kotlin-patterns.disabled`).
///      This is what `Rename-Item` produces on Windows and what the new toggle
///      logic writes.
///   2. Legacy `_disabled/` subdirectory parent — kept for backwards compat
///      with old toggle logic that moved folders into a `_disabled` container.
fn read_skill_meta(dir: &Path) -> (String, String, bool, bool) {
    let raw_dir_name = dir
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("(unnamed)");

    // Convention 1: suffix `.disabled`
    let has_suffix = raw_dir_name.ends_with(".disabled");
    // Convention 2: parent dir named `_disabled`
    let in_disabled_dir = dir
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|s| s.to_str())
        .map(|s| s == "_disabled")
        .unwrap_or(false);

    let enabled = !has_suffix && !in_disabled_dir;

    // The logical name strips the `.disabled` suffix so the UI always shows
    // the clean skill name regardless of enabled state.
    let name = if has_suffix {
        raw_dir_name
            .strip_suffix(".disabled")
            .unwrap_or(raw_dir_name)
            .to_string()
    } else {
        raw_dir_name.to_string()
    };

    let skill_md = dir.join("SKILL.md");
    if !skill_md.is_file() {
        return (name, String::new(), enabled, false);
    }
    let contents = match std::fs::read_to_string(&skill_md) {
        Ok(c) => c,
        Err(_) => return (name, String::new(), enabled, false),
    };
    // Require a YAML frontmatter with at least name + description.
    let trimmed = contents.trim_start();
    let mut has_name = false;
    let mut has_description = false;
    let mut description = String::new();
    if trimmed.starts_with("---") {
        if let Some(end) = trimmed[3..].find("\n---") {
            let block = &trimmed[3..3 + end];
            for raw in block.lines() {
                let t = raw.trim();
                if let Some(rest) = t.strip_prefix("name:") {
                    if !rest.trim().is_empty() {
                        has_name = true;
                    }
                } else if let Some(rest) = t.strip_prefix("description:") {
                    let v = rest.trim().trim_matches(|c| c == '"' || c == '\'');
                    if !v.is_empty() {
                        has_description = true;
                        description = v.to_string();
                    }
                }
            }
        }
    }
    let is_valid_skill = has_name && has_description;
    (name, description, enabled, is_valid_skill)
}

fn collect_skills_from(
    root: &Path,
    origin: SkillOrigin,
    include_disabled: bool,
) -> Vec<SkillEntry> {
    let mut out = Vec::new();
    if !root.exists() {
        return out;
    }
    let Ok(entries) = std::fs::read_dir(root) else {
        return out;
    };
    for e in entries.flatten() {
        let path = e.path();
        if !path.is_dir() {
            continue;
        }
        let dir_name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");

        // Legacy convention: `_disabled/` container directory.
        // Recurse into it and surface each child as a disabled skill.
        if dir_name == "_disabled" {
            if include_disabled {
                if let Ok(disabled) = std::fs::read_dir(&path) {
                    for d in disabled.flatten() {
                        let dp = d.path();
                        if dp.is_dir() {
                            let (n, desc, _, valid) = read_skill_meta(&dp);
                            if !valid {
                                continue;
                            }
                            out.push(SkillEntry {
                                name: n,
                                path: dp.to_string_lossy().to_string(),
                                description: desc,
                                origin: origin.clone(),
                                enabled: false,
                            });
                        }
                    }
                }
            }
            continue;
        }

        // Convention 1: `.disabled` suffix on the folder itself.
        // `read_skill_meta` strips the suffix from the logical name and sets
        // `enabled = false` so we only need to gate on `include_disabled`.
        let has_disabled_suffix = dir_name.ends_with(".disabled");
        if has_disabled_suffix && !include_disabled {
            continue;
        }

        let (n, desc, enabled, valid) = read_skill_meta(&path);
        if !valid {
            // Skip directories without a SKILL.md or without the required
            // YAML frontmatter (`name:` + `description:`). Prevents random
            // markdown subfolders from being surfaced as skills.
            continue;
        }
        out.push(SkillEntry {
            name: n,
            path: path.to_string_lossy().to_string(),
            description: desc,
            origin: origin.clone(),
            enabled,
        });
    }
    out
}

pub fn list_skills_with_origin_inner(
    project_path: Option<String>,
) -> Result<Vec<SkillEntry>, String> {
    let mut out = Vec::new();
    if let Ok(g) = global_skills_dir() {
        out.extend(collect_skills_from(&g, SkillOrigin::Global, true));
    }
    if let Some(p) = project_path.as_deref() {
        let pdir = project_skills_dir(p);
        out.extend(collect_skills_from(&pdir, SkillOrigin::Project, true));
    }
    for plugin_dir in plugin_skills_dirs() {
        out.extend(collect_skills_from(&plugin_dir, SkillOrigin::Plugin, false));
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

/// Toggle a global skill between enabled and disabled.
///
/// **Two on-disk conventions are supported:**
///
/// | Convention | Enabled path | Disabled path |
/// |------------|--------------|---------------|
/// | Suffix (preferred, USER's `Rename-Item` output) | `skills/<name>/` | `skills/<name>.disabled/` |
/// | Legacy container | `skills/<name>/` | `skills/_disabled/<name>/` |
///
/// Toggle resolution order (for enabling):
///   1. Look for `<name>.disabled/` (suffix convention) — rename to `<name>/`.
///   2. Look for `_disabled/<name>/` (legacy) — rename to `<name>/`.
///
/// Toggle resolution order (for disabling):
///   1. Look for `<name>/` — rename to `<name>.disabled/` (suffix convention).
///
/// Disabling always writes the suffix convention going forward. That keeps the
/// output consistent with what `Rename-Item` produces on Windows.
pub fn skill_toggle_inner(name: String, enabled: bool) -> Result<SkillEntry, String> {
    // Path traversal guard: name must not contain path separators.
    if name.contains('/') || name.contains('\\') || name.contains("..") {
        return Err("invalid skill name: path separators not allowed".to_string());
    }

    let root = global_skills_dir()?;

    // Candidate paths for each convention.
    let path_enabled = root.join(&name);
    let path_suffix_disabled = root.join(format!("{}.disabled", name));
    let path_legacy_disabled = root.join("_disabled").join(&name);

    if enabled {
        // Re-enabling: find whichever disabled form exists.
        let from = if path_suffix_disabled.exists() {
            path_suffix_disabled
        } else if path_legacy_disabled.exists() {
            path_legacy_disabled
        } else {
            return Err(format!(
                "skill '{name}' not found in disabled state (checked {}.disabled and _disabled/{name})",
                name
            ));
        };
        if path_enabled.exists() {
            return Err(format!("skill '{name}' already exists at enabled path"));
        }
        std::fs::rename(&from, &path_enabled)
            .map_err(|e| format!("rename {:?} → {:?}: {e}", from, path_enabled))?;
        let (n, desc, e, _) = read_skill_meta(&path_enabled);
        return Ok(SkillEntry {
            name: n,
            path: path_enabled.to_string_lossy().to_string(),
            description: desc,
            origin: SkillOrigin::Global,
            enabled: e,
        });
    }

    // Disabling: always write the suffix convention.
    if !path_enabled.exists() {
        return Err(format!("skill '{name}' not found at enabled path"));
    }
    if path_suffix_disabled.exists() {
        return Err(format!(
            "skill '{name}' already disabled (suffix path exists)"
        ));
    }
    std::fs::rename(&path_enabled, &path_suffix_disabled).map_err(|e| {
        format!(
            "rename {:?} → {:?}: {e}",
            path_enabled, path_suffix_disabled
        )
    })?;
    let (n, desc, e, _) = read_skill_meta(&path_suffix_disabled);
    Ok(SkillEntry {
        name: n,
        path: path_suffix_disabled.to_string_lossy().to_string(),
        description: desc,
        origin: SkillOrigin::Global,
        enabled: e,
    })
}

/// Per-item outcome of a bulk toggle. `error` is `None` on success.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct BulkToggleOutcome {
    pub name: String,
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Aggregate result of `skills_bulk_toggle`. Reports how many slugs flipped
/// successfully plus a per-item breakdown so the UI can surface partial
/// failures (e.g. a skill that was already in the requested state).
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct BulkToggleResult {
    pub requested: usize,
    pub succeeded: usize,
    pub failed: usize,
    pub outcomes: Vec<BulkToggleOutcome>,
}

/// Enable or disable many global skills in one call. `disabled = true` moves
/// each `<name>/` to `<name>.disabled/`; `disabled = false` reverses it.
///
/// Loops the existing `skill_toggle_inner` so the on-disk conventions stay
/// identical to the single-item path. Failures are collected per-item rather
/// than aborting the whole batch — one already-disabled skill must not block
/// the rest of the selection.
pub fn skills_bulk_toggle_inner(
    names: Vec<String>,
    disabled: bool,
) -> Result<BulkToggleResult, String> {
    let enabled = !disabled;
    let mut outcomes: Vec<BulkToggleOutcome> = Vec::with_capacity(names.len());
    let mut succeeded = 0usize;
    let mut failed = 0usize;
    for name in &names {
        match skill_toggle_inner(name.clone(), enabled) {
            Ok(_) => {
                succeeded += 1;
                outcomes.push(BulkToggleOutcome {
                    name: name.clone(),
                    ok: true,
                    error: None,
                });
            }
            Err(e) => {
                failed += 1;
                outcomes.push(BulkToggleOutcome {
                    name: name.clone(),
                    ok: false,
                    error: Some(e),
                });
            }
        }
    }
    Ok(BulkToggleResult {
        requested: names.len(),
        succeeded,
        failed,
        outcomes,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_slug_lower_kebab_only() {
        // Accepted shapes
        assert!(validate_slug("foo").is_ok());
        assert!(validate_slug("foo-bar").is_ok());
        assert!(validate_slug("agent-skills").is_ok());
        assert!(validate_slug("a1").is_ok());

        // Rejected shapes
        assert!(validate_slug("F").is_err(), "single char too short");
        assert!(validate_slug("Foo").is_err(), "uppercase rejected");
        assert!(validate_slug("foo_bar").is_err(), "underscore rejected");
        assert!(validate_slug("foo bar").is_err(), "space rejected");
        assert!(validate_slug("foo/bar").is_err(), "slash rejected");
        // First char must be [a-z0-9] — leading hyphen forbidden
        assert!(validate_slug("-foo").is_err(), "leading hyphen rejected");
    }

    #[test]
    fn sha1_of_file_matches_known_string() {
        // Known: SHA1("abc") = a9993e364706816aba3e25717850c26c9cd0d89d
        let tmp = tempfile::NamedTempFile::new().expect("tempfile");
        std::fs::write(tmp.path(), b"abc").expect("write");
        let hex = sha1_of_file(tmp.path()).expect("sha1 ok");
        assert_eq!(hex, "a9993e364706816aba3e25717850c26c9cd0d89d");
    }

    #[test]
    fn sha1_of_empty_file_matches_known_string() {
        // SHA1("") = da39a3ee5e6b4b0d3255bfef95601890afd80709
        let tmp = tempfile::NamedTempFile::new().expect("tempfile");
        std::fs::write(tmp.path(), b"").expect("write");
        let hex = sha1_of_file(tmp.path()).expect("sha1 ok");
        assert_eq!(hex, "da39a3ee5e6b4b0d3255bfef95601890afd80709");
    }

    #[test]
    fn format_ymd_local_renders_yyyy_mm_dd() {
        // 2026-05-17 00:00:00 UTC = 1778976000 (unix seconds)
        assert_eq!(format_ymd_local(1778976000), "2026-05-17");

        // Epoch
        assert_eq!(format_ymd_local(0), "1970-01-01");

        // 2024-02-29 (leap day) 00:00 UTC = 1709164800
        assert_eq!(format_ymd_local(1709164800), "2024-02-29");
    }

    // -----------------------------------------------------------------------
    // Priority field — KIRKARDO 29
    // -----------------------------------------------------------------------

    /// Build a minimal registry.json string with the given skills and parse it
    /// through `list_skills_inner` logic (using the same types) so we can
    /// assert on sort order without touching the filesystem.
    fn parse_registry_skills(json: &str) -> Vec<SkillInfo> {
        let root: RegistryRoot = serde_json::from_str(json).expect("parse");
        let mut out = Vec::new();
        for (key, s) in root.skills.into_iter() {
            let name = match s.name {
                Some(n) => n,
                None => key.split("::").nth(1).unwrap_or(&key).to_string(),
            };
            let priority = s.priority.map(|p| p.clamp(1, 10)).unwrap_or(5);
            out.push(SkillInfo {
                name,
                state: s.state.unwrap_or_else(|| "unknown".to_string()),
                source: s.source,
                description: s.description.filter(|d| !d.is_empty()),
                tags: s.tags,
                path: s.path,
                usage_count: s.usage_count,
                priority,
                security: s.security,
            });
        }
        out.sort_by(|a, b| b.priority.cmp(&a.priority).then(a.name.cmp(&b.name)));
        out
    }

    #[test]
    fn priority_sort_descending_on_trigger_collision() {
        // Three UI skills with different priorities — mike-tyson (8) must
        // come first, then ui-ux-pro-max (6), then ui-designer (4).
        let json = r#"{
            "skills": {
                "active::mike-tyson":     {"name":"mike-tyson",    "priority":8},
                "active::ui-ux-pro-max":  {"name":"ui-ux-pro-max", "priority":6},
                "active::ui-designer":    {"name":"ui-designer",   "priority":4}
            }
        }"#;
        let skills = parse_registry_skills(json);
        assert_eq!(skills[0].name, "mike-tyson");
        assert_eq!(skills[0].priority, 8);
        assert_eq!(skills[1].name, "ui-ux-pro-max");
        assert_eq!(skills[1].priority, 6);
        assert_eq!(skills[2].name, "ui-designer");
        assert_eq!(skills[2].priority, 4);
    }

    #[test]
    fn missing_priority_defaults_to_five() {
        // A skill without a `priority` key should resolve to 5.
        let json = r#"{
            "skills": {
                "active::no-priority": {"name":"no-priority"}
            }
        }"#;
        let skills = parse_registry_skills(json);
        assert_eq!(skills[0].priority, 5);
    }

    #[test]
    fn priority_out_of_range_is_clamped() {
        // Values outside 1..=10 are clamped rather than rejected so a corrupt
        // registry.json does not panic the UI.
        let json = r#"{
            "skills": {
                "active::too-high": {"name":"too-high", "priority":99},
                "active::too-low":  {"name":"too-low",  "priority":0}
            }
        }"#;
        let skills = parse_registry_skills(json);
        let high = skills.iter().find(|s| s.name == "too-high").unwrap();
        let low = skills.iter().find(|s| s.name == "too-low").unwrap();
        assert_eq!(high.priority, 10, "values >10 clamped to 10");
        assert_eq!(low.priority, 1, "values <1 clamped to 1");
    }

    // -----------------------------------------------------------------------
    // Bulk toggle
    // -----------------------------------------------------------------------

    #[test]
    fn bulk_toggle_aggregates_per_item_outcomes() {
        // Use slugs that cannot exist as enabled/disabled global skills so
        // every item takes the error path deterministically (no real skill is
        // named like this). The point is to assert the aggregation shape, not
        // to mutate the user's real skills dir.
        let names = vec![
            "zzz-bulk-test-nonexistent-a".to_string(),
            "zzz-bulk-test-nonexistent-b".to_string(),
        ];
        let res = skills_bulk_toggle_inner(names.clone(), true).expect("bulk ok");
        assert_eq!(res.requested, 2);
        assert_eq!(res.outcomes.len(), 2);
        // Both are missing → both fail, none succeed, totals add up.
        assert_eq!(res.succeeded + res.failed, res.requested);
        assert!(res.outcomes.iter().all(|o| !o.ok && o.error.is_some()));
        assert_eq!(res.outcomes[0].name, names[0]);
    }

    #[test]
    fn bulk_toggle_empty_is_noop() {
        let res = skills_bulk_toggle_inner(vec![], false).expect("bulk ok");
        assert_eq!(res.requested, 0);
        assert_eq!(res.succeeded, 0);
        assert_eq!(res.failed, 0);
        assert!(res.outcomes.is_empty());
    }

    #[test]
    fn tie_broken_alphabetically() {
        // Two skills with same priority — alphabetical tiebreak must be stable.
        let json = r#"{
            "skills": {
                "active::zebra": {"name":"zebra", "priority":7},
                "active::alpha": {"name":"alpha", "priority":7}
            }
        }"#;
        let skills = parse_registry_skills(json);
        assert_eq!(skills[0].name, "alpha");
        assert_eq!(skills[1].name, "zebra");
    }
}
