// Diagnostics — static catalogs (COMMON_ERRORS, FIX_CATALOG, KNOWN_ERRORS, etc.)

import type { CommonError, CommonErrorCategory, Fix, FixCategory, KnownError } from "./types";

// ---------------------------------------------------------------------------
// COMMON_ERRORS catalog — 13 errores reconocibles con check + fix
// ---------------------------------------------------------------------------

export const COMMON_ERRORS: CommonError[] = [
  {
    id: "claude-login-expired",
    category: "AI / Claude",
    severity: "critical",
    title: "Claude Code login expired",
    symptom: "Terminal shows 'authentication required' or spawned sessions fail immediately.",
    checkId: "claude-login-expired",
    primaryFixKind: null,
    primaryFixLabel: "Run claude /login in terminal",
    extraFixes: [],
  },
  {
    id: "ai-router-no-keys",
    category: "AI / Claude",
    severity: "warning",
    title: "AI Router: no providers configured",
    symptom: "AI Router falls back to Claude-only mode; Codex / Gemini routing never triggers.",
    checkId: "ai-router-no-keys",
    primaryFixKind: null,
    primaryFixLabel: "Open Settings > API Keys",
    extraFixes: [],
  },
  {
    id: "node-not-found",
    category: "AI / Claude",
    severity: "critical",
    title: "Node.js not in PATH",
    symptom: "Claude Code CLI cannot be installed or updated; npm commands fail.",
    checkId: "node-not-found",
    primaryFixKind: null,
    primaryFixLabel: "Install Node.js (nodejs.org)",
    extraFixes: [],
  },
  {
    id: "network-unreachable",
    category: "Network",
    severity: "critical",
    title: "Network unreachable",
    symptom: "All AI providers timeout; API calls fail with ECONNREFUSED / ERR_NETWORK.",
    checkId: "network-unreachable",
    primaryFixKind: "pc-flush-dns",
    primaryFixLabel: "Flush DNS",
    extraFixes: [
      { kind: "pc-renew-ip", label: "Renew IP" },
      { kind: "pc-net-reset-all", label: "Full network reset" },
      { kind: "pc-network-troubleshooter", label: "Network troubleshooter" },
    ],
  },
  {
    id: "port-1420-in-use",
    category: "System",
    severity: "warning",
    title: "Port 1420 in use",
    symptom: "Control Center fails to start with EADDRINUSE — another instance may be running.",
    checkId: "port-1420-in-use",
    primaryFixKind: null,
    primaryFixLabel: "Kill process on port 1420",
    extraFixes: [
      { kind: "pc-task-manager", label: "Open Task Manager" },
    ],
  },
  {
    id: "gh-cli-missing",
    category: "System",
    severity: "warning",
    title: "gh CLI missing",
    symptom: "GitHub operations in workflows fail; 'gh' command not recognized.",
    checkId: "gh-cli-missing",
    primaryFixKind: null,
    primaryFixLabel: "scoop install gh",
    extraFixes: [],
  },
  {
    id: "tauri-capabilities-denied",
    category: "System",
    severity: "warning",
    title: "Tauri capabilities issue",
    symptom: "Shell commands silently fail; file dialogs don't open; permissions errors in logs.",
    checkId: "tauri-capabilities-denied",
    primaryFixKind: null,
    primaryFixLabel: "Check capabilities/default.json",
    extraFixes: [
      { kind: "pc-event-viewer", label: "Open Event Viewer" },
    ],
  },
  {
    id: "qdrant-binary-missing",
    category: "AI / Claude",
    severity: "info",
    title: "Qdrant binary not found",
    symptom: "Vector search / ECC local KG features unavailable; graphify indexing fails.",
    checkId: "qdrant-binary-missing",
    primaryFixKind: null,
    primaryFixLabel: "Download qdrant.exe",
    extraFixes: [],
  },
  {
    id: "plugins-out-of-date",
    category: "Plugins",
    severity: "info",
    title: "Plugins may be out of date",
    symptom: "ECC hooks not triggering; plugin features behave unexpectedly.",
    checkId: "plugins-out-of-date",
    primaryFixKind: null,
    primaryFixLabel: "Check plugin updates",
    extraFixes: [],
  },
  {
    id: "hooks-misconfigured",
    category: "Plugins",
    severity: "warning",
    title: "Hooks misconfigured",
    symptom: "PostToolUse / Stop hooks are not firing; auto-format or cost-watchdog inactive.",
    checkId: "hooks-misconfigured",
    primaryFixKind: null,
    primaryFixLabel: "Open ~/.claude/settings.json",
    extraFixes: [],
  },
  {
    id: "ultron-disk-usage",
    category: "Storage",
    severity: "info",
    title: ".ultron disk usage high",
    symptom: "~/.ultron folder has grown large; old diagnostics, sessions or logs piling up.",
    checkId: "ultron-disk-usage",
    primaryFixKind: "pc-clear-temp",
    primaryFixLabel: "Clear %TEMP%",
    extraFixes: [
      { kind: "pc-disk-cleanup", label: "Disk Cleanup" },
    ],
  },
  {
    id: "projects-json-missing",
    category: "Storage",
    severity: "critical",
    title: "projects.json missing or corrupt",
    symptom: "Projects tab is empty; Control Center shows 'no projects found' on every launch.",
    checkId: "projects-json-missing",
    primaryFixKind: null,
    primaryFixLabel: "Open cockpit folder",
    extraFixes: [
      { kind: "pc-event-viewer", label: "Open Event Viewer" },
    ],
  },
  {
    id: "git-uncommitted-cockpit",
    category: "Git",
    severity: "info",
    title: "Uncommitted changes in cockpit",
    symptom: "kanban, workdays or project data changed locally but not committed to git.",
    checkId: "git-uncommitted-cockpit",
    primaryFixKind: null,
    primaryFixLabel: "Open terminal to commit",
    extraFixes: [],
  },
];

export const COMMON_ERROR_CATEGORIES: CommonErrorCategory[] = [
  "AI / Claude",
  "Network",
  "Storage",
  "Plugins",
  "System",
  "Git",
];

// ---------------------------------------------------------------------------
// FIX_CATALOG (Windows PC fixes)
// ---------------------------------------------------------------------------

export const FIX_CATALOG: Record<string, Fix> = {
  "pc-flush-dns": { kind: "pc-flush-dns", label: "Flush DNS", detail: "ipconfig /flushdns — clears the local DNS resolver cache.", category: "network" },
  "pc-renew-ip": { kind: "pc-renew-ip", label: "Renew IP", detail: "ipconfig /release && /renew — releases and re-acquires the DHCP lease.", category: "network" },
  "pc-reset-network": { kind: "pc-reset-network", label: "Reset TCP/IP", detail: "netsh int ip reset — resets the Windows TCP/IP stack. Reboot recommended.", category: "network", confirm: { title: "Reset TCP/IP stack?", message: "Drops your current connection and a reboot is recommended afterwards. Continue?" } },
  "pc-winsock-reset": { kind: "pc-winsock-reset", label: "Reset Winsock", detail: "netsh winsock reset — restores Winsock catalog to default. Reboot recommended.", category: "network", confirm: { title: "Reset Winsock?", message: "Some third-party LSPs may need to be re-registered. Continue?" } },
  "pc-reset-firewall": { kind: "pc-reset-firewall", label: "Reset firewall", detail: "netsh advfirewall reset — restores Windows Firewall to defaults.", category: "network", confirm: { title: "Reset Windows Firewall?", message: "Removes all custom inbound/outbound rules. Continue?" } },
  "pc-flush-arp": { kind: "pc-flush-arp", label: "Flush ARP cache", detail: "netsh interface ip delete arpcache — clears the local ARP table.", category: "network" },
  "pc-net-reset-all": { kind: "pc-net-reset-all", label: "Full network reset", detail: "release + flushdns + renew + winsock reset + TCP/IP reset, in that order. Reboot recommended.", category: "network", confirm: { title: "Run full network reset?", message: "Releases DHCP, flushes DNS, renews IP, then resets Winsock and TCP/IP. A reboot is recommended afterwards. Continue?" } },
  "pc-network-troubleshooter": { kind: "pc-network-troubleshooter", label: "Network troubleshooter", detail: "Launches the Windows built-in Network Adapter Diagnostic wizard.", category: "network" },
  "pc-network-connections": { kind: "pc-network-connections", label: "Network connections", detail: "Opens ncpa.cpl — classic adapter list.", category: "network" },
  "pc-open-hosts": { kind: "pc-open-hosts", label: "Open hosts file", detail: "Opens C:\\Windows\\System32\\drivers\\etc\\hosts in Notepad.", category: "network" },
  "pc-restart-spooler": { kind: "pc-restart-spooler", label: "Restart Print Spooler", detail: "Restart-Service Spooler — fixes hung print queue / spooler crashes.", category: "services" },
  "pc-restart-audio": { kind: "pc-restart-audio", label: "Restart Audio service", detail: "Restart-Service Audiosrv + AudioEndpointBuilder.", category: "services" },
  "pc-restart-bluetooth": { kind: "pc-restart-bluetooth", label: "Restart Bluetooth", detail: "Restart-Service bthserv — Bluetooth Support service.", category: "services" },
  "pc-restart-wsearch": { kind: "pc-restart-wsearch", label: "Restart Windows Search", detail: "Restart-Service WSearch — fixes broken Start menu search.", category: "services" },
  "pc-restart-bits": { kind: "pc-restart-bits", label: "Restart BITS", detail: "Restart-Service BITS — Background Intelligent Transfer Service.", category: "services" },
  "pc-restart-wuauserv": { kind: "pc-restart-wuauserv", label: "Restart Update service", detail: "Restart-Service wuauserv — Windows Update service.", category: "services" },
  "pc-restart-time": { kind: "pc-restart-time", label: "Restart Time service", detail: "Restart-Service w32time + w32tm /resync — fixes clock skew.", category: "services" },
  "pc-services-mmc": { kind: "pc-services-mmc", label: "Open services.msc", detail: "Launches the Services management console.", category: "services" },
  "pc-repair-wu": { kind: "pc-repair-wu", label: "Repair Windows Update", detail: "Stops wuauserv + BITS, wipes SoftwareDistribution, restarts them.", category: "update", confirm: { title: "Repair Windows Update?", message: "Stops Windows Update services, deletes SoftwareDistribution, then restarts them. Continue?" } },
  "pc-reset-wu-components": { kind: "pc-reset-wu-components", label: "Reset WU components", detail: "Stops wuauserv+bits+cryptsvc+msiserver, wipes SoftwareDistribution + catroot2, restarts.", category: "update", confirm: { title: "Reset Windows Update components?", message: "Stops wuauserv, bits, cryptsvc and msiserver, then wipes SoftwareDistribution and catroot2. Continue?" } },
  "pc-wu-troubleshooter": { kind: "pc-wu-troubleshooter", label: "WU troubleshooter", detail: "Launches the Windows Update Diagnostic wizard (msdt).", category: "update" },
  "pc-windows-update": { kind: "pc-windows-update", label: "Open Windows Update", detail: "Opens ms-settings:windowsupdate.", category: "update" },
  "pc-wsreset": { kind: "pc-wsreset", label: "Reset Store cache", detail: "wsreset.exe — clears the Microsoft Store cache.", category: "update" },
  "pc-reregister-store-apps": { kind: "pc-reregister-store-apps", label: "Re-register Store apps", detail: "Get-AppxPackage | Add-AppxPackage — re-registers all Microsoft Store apps.", category: "update", confirm: { title: "Re-register all Store apps?", message: "Walks every installed AppX package and re-registers it. Takes a few minutes. Continue?" } },
  "pc-sfc": { kind: "pc-sfc", label: "Run SFC scan", detail: "sfc /scannow — verify + restore system files. Opens a new console.", category: "storage" },
  "pc-dism": { kind: "pc-dism", label: "Run DISM repair", detail: "DISM /Online /Cleanup-Image /RestoreHealth — repairs the component store.", category: "storage" },
  "pc-chkdsk": { kind: "pc-chkdsk", label: "Run chkdsk (scan)", detail: "chkdsk C: /scan — read-only scan of the system drive.", category: "storage" },
  "pc-clear-temp": { kind: "pc-clear-temp", label: "Clear %TEMP%", detail: "Deletes everything under %TEMP%. Locked files are skipped.", category: "storage", confirm: { title: "Clear temp files?", message: "Permanently deletes contents of %TEMP%. Continue?" } },
  "pc-disk-cleanup": { kind: "pc-disk-cleanup", label: "Disk Cleanup", detail: "Launches cleanmgr.exe.", category: "storage" },
  "pc-disk-management": { kind: "pc-disk-management", label: "Disk Management", detail: "Opens diskmgmt.msc — partition + volume manager.", category: "storage" },
  "pc-restart-explorer": { kind: "pc-restart-explorer", label: "Restart Explorer", detail: "Kills + relaunches explorer.exe. Fixes taskbar / shell glitches.", category: "shell", confirm: { title: "Restart Explorer?", message: "Closes any open File Explorer windows. Taskbar will blink. Continue?" } },
  "pc-mdsched": { kind: "pc-mdsched", label: "Memory diagnostic", detail: "Launches mdsched.exe — schedules a RAM check at next reboot.", category: "diagnostic" },
  "pc-power-troubleshooter": { kind: "pc-power-troubleshooter", label: "Power troubleshooter", detail: "Launches the Windows Power Diagnostic wizard.", category: "diagnostic" },
  "pc-audio-troubleshooter": { kind: "pc-audio-troubleshooter", label: "Audio troubleshooter", detail: "Launches the Audio Playback Diagnostic wizard.", category: "diagnostic" },
  "pc-bluetooth-troubleshooter": { kind: "pc-bluetooth-troubleshooter", label: "Bluetooth troubleshooter", detail: "Launches the Bluetooth Diagnostic wizard.", category: "diagnostic" },
  "pc-search-troubleshooter": { kind: "pc-search-troubleshooter", label: "Search troubleshooter", detail: "Launches the Search & Indexing Diagnostic wizard.", category: "diagnostic" },
  "pc-event-viewer": { kind: "pc-event-viewer", label: "Open Event Viewer", detail: "Launches eventvwr.msc for deeper inspection.", category: "diagnostic" },
  "pc-reliability-monitor": { kind: "pc-reliability-monitor", label: "Reliability Monitor", detail: "perfmon /rel — per-day system stability log.", category: "diagnostic" },
  "pc-resource-monitor": { kind: "pc-resource-monitor", label: "Resource Monitor", detail: "resmon.exe — per-process CPU/memory/disk/network.", category: "diagnostic" },
  "pc-perfmon": { kind: "pc-perfmon", label: "Performance Monitor", detail: "perfmon.exe — full counter graph.", category: "diagnostic" },
  "pc-task-manager": { kind: "pc-task-manager", label: "Task Manager", detail: "Launches taskmgr.exe.", category: "diagnostic" },
  "pc-device-manager": { kind: "pc-device-manager", label: "Device Manager", detail: "Launches devmgmt.msc.", category: "system" },
  "pc-gpupdate": { kind: "pc-gpupdate", label: "gpupdate /force", detail: "Forces Group Policy refresh.", category: "system" },
  "pc-computer-management": { kind: "pc-computer-management", label: "Computer Management", detail: "Opens compmgmt.msc — full MMC console.", category: "system" },
  "pc-task-scheduler": { kind: "pc-task-scheduler", label: "Task Scheduler", detail: "Opens taskschd.msc.", category: "system" },
  "pc-programs-features": { kind: "pc-programs-features", label: "Programs & Features", detail: "Opens appwiz.cpl — installed software list.", category: "system" },
  "pc-power-options": { kind: "pc-power-options", label: "Power Options", detail: "Opens powercfg.cpl.", category: "system" },
  "pc-sound-settings": { kind: "pc-sound-settings", label: "Sound settings", detail: "Opens mmsys.cpl — playback / recording devices.", category: "system" },
  "pc-windows-security": { kind: "pc-windows-security", label: "Windows Security", detail: "Opens windowsdefender: settings.", category: "system" },
  "pc-recovery": { kind: "pc-recovery", label: "Recovery options", detail: "Opens ms-settings:recovery.", category: "system" },
  "pc-system-restore": { kind: "pc-system-restore", label: "System Restore", detail: "Launches rstrui.exe.", category: "system" },
};

export const CATEGORY_LABELS: Record<FixCategory, string> = {
  network: "Network",
  services: "Services",
  update: "Windows Update / Store",
  storage: "Storage & integrity",
  shell: "Shell",
  diagnostic: "Diagnostic tools",
  system: "System & management",
};

export const CATEGORY_ORDER: FixCategory[] = [
  "network", "services", "update", "storage", "shell", "diagnostic", "system",
];

// ---------------------------------------------------------------------------
// Known Windows Event IDs
// ---------------------------------------------------------------------------

export const KNOWN_ERRORS: Record<number, KnownError> = {
  41: { description: "Kernel-Power — system rebooted without cleanly shutting down (hard crash, power loss or driver hang).", fixes: ["pc-mdsched", "pc-power-troubleshooter", "pc-reliability-monitor", "pc-event-viewer", "pc-device-manager", "pc-sfc", "pc-dism", "pc-chkdsk"], severity: "critical" },
  1001: { description: "Windows Error Reporting — an application or driver crashed and was bucketed by WER.", fixes: ["pc-event-viewer", "pc-reliability-monitor", "pc-sfc", "pc-dism", "pc-restart-explorer"], severity: "error" },
  6008: { description: "Unexpected shutdown — the previous system shutdown was not clean (forced reboot, BSOD, power loss).", fixes: ["pc-mdsched", "pc-chkdsk", "pc-power-troubleshooter", "pc-reliability-monitor", "pc-event-viewer"], severity: "critical" },
  7000: { description: "Service failed to start — a Windows service could not be launched.", fixes: ["pc-services-mmc", "pc-event-viewer", "pc-sfc", "pc-dism"], severity: "error" },
  7001: { description: "Service depends on a service which failed to start — a dependency chain broke.", fixes: ["pc-services-mmc", "pc-event-viewer"], severity: "error" },
  7011: { description: "Service timeout — Windows gave up waiting for a service to respond (default 30s).", fixes: ["pc-services-mmc", "pc-restart-explorer"], severity: "warning" },
  7031: { description: "A service crashed and SCM is attempting recovery.", fixes: ["pc-services-mmc", "pc-event-viewer", "pc-restart-wsearch", "pc-restart-bits"], severity: "warning" },
  4625: { description: "Failed logon attempt — wrong password, expired account or locked out.", fixes: ["pc-event-viewer", "pc-gpupdate"], severity: "warning" },
  1000: { description: "Application Error — a user-mode process crashed (AppCrash bucket).", fixes: ["pc-event-viewer", "pc-sfc", "pc-dism", "pc-clear-temp", "pc-restart-explorer"], severity: "error" },
  10010: { description: "DCOM server did not register with DCOM within the required timeout.", fixes: ["pc-event-viewer", "pc-services-mmc", "pc-sfc"], severity: "warning" },
  372: { description: "Print Spooler error — the spooler service has hit an error condition.", fixes: ["pc-restart-spooler", "pc-services-mmc", "pc-clear-temp"], severity: "error" },
  20: { description: "Windows Update installation failure (WUA).", fixes: ["pc-repair-wu", "pc-reset-wu-components", "pc-restart-wuauserv", "pc-restart-bits", "pc-windows-update", "pc-wu-troubleshooter", "pc-sfc"], severity: "error" },
  25: { description: "Windows Update download failure.", fixes: ["pc-repair-wu", "pc-restart-bits", "pc-restart-wuauserv", "pc-network-troubleshooter", "pc-flush-dns"], severity: "warning" },
  7034: { description: "A service terminated unexpectedly. SCM is logging the crash; check the source service.", fixes: ["pc-services-mmc", "pc-event-viewer", "pc-restart-wsearch", "pc-restart-bits", "pc-sfc"], severity: "error" },
  7: { description: "Disk has a bad block — possible hardware failure starting.", fixes: ["pc-chkdsk", "pc-event-viewer", "pc-reliability-monitor", "pc-disk-management"], severity: "critical" },
  219: { description: "A driver was not installed correctly — likely missing or incompatible.", fixes: ["pc-device-manager", "pc-event-viewer", "pc-sfc"], severity: "warning" },
  153: { description: "An IO operation was retried after a timeout — possible disk issues.", fixes: ["pc-chkdsk", "pc-event-viewer", "pc-disk-management"], severity: "warning" },
  10016: { description: "DCOM permission denied — Local Activation not granted.", fixes: ["pc-event-viewer", "pc-services-mmc", "pc-gpupdate"], severity: "warning" },
  1003: { description: "BugCheck — the system crashed and produced a kernel dump (BSOD).", fixes: ["pc-mdsched", "pc-reliability-monitor", "pc-event-viewer", "pc-sfc", "pc-dism", "pc-device-manager"], severity: "critical" },
  1002: { description: "Application hang — a process stopped responding to Windows.", fixes: ["pc-event-viewer", "pc-reliability-monitor", "pc-clear-temp", "pc-restart-explorer"], severity: "warning" },
};

export const GENERIC_FIXES = ["pc-event-viewer", "pc-reliability-monitor", "pc-services-mmc", "pc-sfc", "pc-dism", "pc-network-troubleshooter"];
